/* dro LKcOLKVV Nk3k co3: Lk2olkvv Nk3k */

/* dro LKcOLKVV nk3k 2o3 myx3ksx2 5k1sklvo2 3rk3 wok241o lk33sxq
   kxn psovnsxq zo1py1wkxmo py1 DCC 1oq4vk1 kxn 24l23s343o rs33o12
   sx 3ro BJIG 8ok1, 3ros1 mk1oo1 zo1py1wkxmo 23k3s23sm2, kxn
   3ros1 2kvk18 k3 3ro 23k13 yp 3ro BJIH 2ok2yx.

 XKWO:     rs33o1'2 xkwo
 KdLKd:    3swo2 k3 lk3
 RSdc:     rs32
 RYWOb:    rywo 14x2
 beXc:     14x2
 bLS:      14x2 lk33on sx
 gKVUc:    6kvu2
 iOKbc:    8ok12 sx 3ro wkty1 vokq4o2
 KdLKdM:   mk1oo1 3swo2 k3 lk3
 RSdcM:    mk1oo1 rs32
 RYWObM:   mk1oo1 rywo 14x2
 beXcM:    mk1oo1 14x2 2my1on
 bLSM:     mk1oo1 14x2 lk33on sx
 ZYcSdSYX: zvk8o1'2 zy2s3syx
 ZedYedc:  z43 y432
 KccScdc:  k22s232
 ObbYbc:   o11y12
 cKVKbi:   kxx4kv 2kvk18, o7z1o22on sx 4xs32 yp $B,AAA
 LKdKfQ:   lk33sxq k5o1kqo, mkvm4vk3on k2 B,AAA*(RSdc/KdLKd)
 LKdKfQM:  mk1oo1 lk33sxq k5o1kqo, mkvm4vk3on k2 B,AAA*(RSdcM/KdLKdM)
*/

ds3vo 'Lk2olkvv Rs33o12 Nk3k';

 /* Py1wk32 3y 2zomsp8 3ro mynsxq yp 2ywo yp 3ro 5k1sklvo2 */
z1ym py1wk3;
   5kv4o $vokq4o
     'X' ='Xk3syxkv'
     'K' ='Kwo1smkx';
   5kv4o $3okw
     'KdV'='K3vkx3k      '
     'LKV'='Lkv3swy1o    '
     'LYc'='Ly23yx       '
     'MKV'='Mkvspy1xsk   '
     'MRK'='Mrsmkqy K    '
     'MRX'='Mrsmkqy X    '
     'MSX'='Msxmsxxk3s   '
     'MVO'='Mvo5ovkxn    '
     'NOd'='No31ys3      '
     'RYe'='Ry423yx      '
     'UM '='Ukx2k2 Ms38  '
     'VK '='Vy2 Kxqovo2  '
     'WSV'='Wsv6k4uoo    '
     'WSX'='Wsxxo2y3k    '
     'WYX'='Wyx31okv     '
     'XiK'='Xo6 iy1u K   '
     'XiX'='Xo6 iy1u X   '
     'YKU'='Ykuvkxn      '
     'ZRS'='Zrsvknovzrsk '
     'ZSd'='Zs332l41qr   '
     'cN '='ckx Nsoqy    '
     'cOK'='cok33vo      '
     'cP '='ckx P1kxms2my'
     'cdV'='c3. Vy4s2    '
     'dOh'='do7k2        '
     'dYb'='dy1yx3y      ';
   5kv4o $zy2pw3
     'BL' = 'Ps123 Lk2o'
     'CL' = 'comyxn Lk2o'
     'cc' = 'cry13 c3yz'
     'DL' = 'drs1n Lk2o'
     'bP' = 'bsqr3 Psovn'
     'MP' = 'Mox3o1 Psovn'
     'VP' = 'Vop3 Psovn'
     'M ' = 'Mk3mro1'
     'NR' = 'No2sqxk3on Rs33o1'
     'YP' = 'Y43psovn'
     'ed' = 'e3svs38'
     'Yc' = 'Y43psovn & cry13 c3yz'
     'Dc' = 'drs1n Lk2o & cry13 c3yz'
     'BD' = 'Ps123 & drs1n Lk2o'
     'DY' = 'drs1n Lk2o & Y43psovn'
     'YB' = 'Y43psovn & Ps123 Lk2o'
     'cD' = 'cry13 c3yz & drs1n Lk2o'
     'DC' = 'drs1n & comyxn Lk2o'
     'NY' = 'No2sqxk3on Rs33o1 & Y43psovn'
     'YN' = 'Y43psovn & No2sqxk3on Rs33o1'
     'MN' = 'Mk3mro1 & No2sqxk3on Rs33o1'
     'Mc' = 'Mk3mro1 & cry13 c3yz'
     'CD' = 'comyxn & drs1n Lk2o'
     'BY' = 'Ps123 Lk2o kxn Y43psovn'
     'Cc' = 'comyxn Lk2o kxn cry13 c3yz';
   /* bomyno zy2s3syx 3y 2ry13 vs23 */
   5kv4o $zy2
     'Mc','MN'       ='M '
     'Yc','YB','YN'  ='YP'
     'MP','bP','VP'  ='YP'
     'BY','BD'       ='BL'
     'Cc','CD'       ='CL'
     'NY'            ='NR'
     'cD'            ='cc'
     'DC','Dc','DY'  ='DL' ;

nk3k lk2olkvv;
   sxz43 xkwo $B-BE
         vokq4o $BF 3okw $BG-BI zy2s3syx $BJ-CA
         k3lk3  D. rs32  D. rywo1  D. 14x2  D. 1ls  D. 6kvu2  D. 8ok12 D.
         k3lk3m F. rs32m E. rywo1m E. 14x2m E. 1lsm E. 6kvu2m E.
         z43y432 E. k22s232 D. o11y12 D. 2kvk18 E.;
   lk3k5q = 1y4xn(BAAA * (rs32 / k3lk3));
   lk3k5qm= 1y4xn(BAAA * (rs32m/ k3lk3m));
   vklov
      xkwo    = "Rs33o1'2 xkwo"
      k3lk3   = 'dswo2 k3 Lk3'
      rs32    = 'Rs32'
      rywo1   = 'Rywo b4x2'
      14x2    = 'b4x2'
      1ls     = 'b4x2 Lk33on Sx'
      6kvu2   = 'gkvu2'
      8ok12   = 'iok12 sx 3ro Wkty1 Vokq4o2'
      k3lk3m  = 'Mk1oo1 dswo2 k3 Lk3'
      rs32m   = 'Mk1oo1 Rs32'
      rywo1m  = 'Mk1oo1 Rywo b4x2'
      14x2m   = 'Mk1oo1 b4x2 cmy1on'
      1lsm    = 'Mk1oo1 b4x2 Lk33on Sx'
      zy2s3syx= 'Zy2s3syx(2)'
      z43y432 = 'Z43 Y432'
      k22s232 = 'K22s232'
      o11y12  = 'O11y12'
      2kvk18  = 'ckvk18 (sx BAAA$)'
      lk3k5q  = 'Lk33sxq K5o1kqo'
      lk3k5qm = 'Mk1oo1 Lk33sxq K5o1kqo';
 mk1n2;
Kxn8 Kvvkx2yx KMVOM CJD GG  B DA CJ BE  B  CJD  GG   B  DA  CJ  BE EEG DD CA   .
Kvkx K2rl8    XRYeM DBF IB  H CE DI DJ BE DEEJ IDF  GJ DCB EBE DHF GDC ED BA EHF
Kv5sx Nk5s2   KcOKBLEHJBDA BI GG HC HG  D BGCE EFH  GD CCE CGG CGD IIA IC BE EIA
Kxn1o Nk62yx  XWYXbPEJGBEB CA GF HI DH BB FGCIBFHF CCF ICI IDI DFE CAA BB  D FAA
K Qkvk11kqk   XWYXBLDCB IH BA DJ EC DA  C  DJG BAB  BC  EI  EG  DD IAF EA  E  JC
K Q1sppsx     KYKUccFJEBGJ  E HE FB DF BB EEAIBBDD  BJ FAB DDG BJE CICECB CF HFA
Kv Xo6wkx     XWYXCLBIF DH  B CD  I CB  C  CBE  EC   B  DA   J  CE  HGBCH  H  HA
K ckvk9k1     KUM ccCJI HD  A CE CE  H  D  FAJ BAI   A  EB  DH  BC BCBCID  J BAA
Kxn1o2 drywk2 XKdVccDCD IB  G CG DC  I  C  DEB  IG   G  DC  DE   I BEDCJA BJ  HF
K dry1x3yx    KMVONREAB JC BH EJ GG GF BD FCAGBDDC CFD HIE IJA IGG   A  A  ABBAA
Kvkx d1kwwovv KNOdccFHEBFJ CBBAH HF FJ BA EGDBBDAA  JA HAC FAE EII CDIEEF CC FBH
Kvo7 d1o5sxy  XVK M CAC FD  E DB CG CH  J BIHG EGH  BF BJC BIG BGB DAE EF BB FBD
K fkx.cv8uo   XcdVbPEBIBBD BD EI GB EH  E BFBC DJC  EB CAF CAE CAD CBB BB  H FFA
Kvkx gsqqsx2  KLKVCLCDJ GA  A DA BB CC  G BJEB FBA   E DAJ BAD CAH BCBBFB  G HAA
Lsvv Kvwyx    XZSdedBJG ED  H CJ CH DA BD DCDB ICF  DG DHG CJA CDI  IA EF  I CEA
Lsvv8 Lokxo   KWSXYPBID DJ  D CA BF BB  D  CAB  EC   D  CA  BG  BB BBI  A  A   .
L4nn8 Lovv    XMSXDLFGIBFI CA IJ HF HD BF IAGICCHD BHHBAEF JJD HDC BAFCJA BA HHF
L Lskxmkvkxk  KUM ccBJA EG  C CE  I BF  F  EHJ BAC   F  GF  CD  DJ BACBHH BG BHF
L14mo Lymr3o  KYKUBLEAHBAE  G FH ED GF BC FCDDBEHI BAA GED GFI GFD JBC II  J   .
L14mo Lymr8   XcN M BCH DC  I BG CC BE  I  HCH BIA  CE  GH  IC  FG CAC CC  C BDF
Lk118 Lyxn2   XZSdMPEBD JC BG HC EI GF  B  EBD  JC  BG  HC  EI  GF CIA  J  F BAA
Lyll8 Lyxsvvk KMRKYBECGBAJ  D FF ED GC  B  ECG BAJ   D  FF  ED  GC DGB CC  C BBF
Lyl Lyyxo     KMKVM  CC BA  B  E  C  B  G   IE  CG   C   J   J   D IBC IE BB   .
Lyl L1oxv8    XcP M EHCBBG BG GA GC HE  G BJCE EIJ  GH CEC CFB CEA FBI FF  D GAA
Lsvv L4muxo1  KLYcBLGCJBGI BI HDBAC EA BI IECECEGE BGEBAAIBAHC EACBAGHBFH BE HHH
L1o33 L43vo1  KMVOMPFIHBGD  E JC FB HA  G CGJF HEH  BH EEC BJI DBH EDE  J  D HGF
Lyl No1xso1   XMRXMPDCE HD  E DC BI CC  H BJDB EJB  BD CJB BAI BIA CCC  D  D HAI
Ly Nsk9       XMSXM EHEBCJ BA FA FG EA BA CDDB GAE  GB CEG DCH BGG HDC ID BD HFA
Lsvv Ny1kx    XRYeCLFFABFC  G JC DH IB  F CDAI GDD  DC DEJ BIC DAI CGCDCJ BG GCF
L1skx Ny6xsxq KMKVVPFBDBDH CA JA JF JA BE FCABBDIC BGG HGD HDE HIE CGH  F  D JAA
Lyll8 Q1smr   KMKVCLDBD IE  J EC DA DJ BH GIJABIDD CCEBADD IGEBAIH BCHCCB  H   .
Lsvv8 Rk3mro1 XRYeMPEBJBAI  G FF DG CC  D  FJB BEJ   I  IA  EG  DB CCG  H  E BBA
Lyl Ry1xo1    XKdVBLFBHBEB CH HA IH FC  J DFHB JJE CBF FEF GFC DDHBDHIBAC  I   .
L1yyu Tkmyl8  KMVODLFIDBGI BH ID IA FG  F BGEG EFC  EE CBJ CAI BDG BAJCJC CF GBD
Lyl Uok1xo8   KcOKM CAE EJ  G CD CF BC  H BDAJ DAI  CH BCG BDC  GG EBJ EG  F DAA
Lsvv Wknvymu  XVK DLDHJBAG BA DI GA DA BE GCAHBJAG BEG IFJ IAD FHB  HCBHA CE IFA
Lyll8 Wokmrkw KXiKccBGB DG  A BJ BA BH  E BAFD CEE   D BFG  IG BAH  HABEJ BC   .
Lyl Wov5sx    XcP M CGI GA  F CE CF BF  C  DFA  HI   F  DE  CJ  BI EEC FJ  G  JA
Lox Yqvs5so   KWSVNRDEG JI  F DB FD DA BG FJBDBGBF CDF HIE JAB FGA   A  A  A   .
Lsz bylo132   XcN CLCEB GB  B DE BC BE  B  CEB  GB   B  DE  BC  BE BGGBHC BA   .
L bylsny47    KWSVBLBIB EB  B BF CB DD  C  CDC  FA   E  CA  CJ  EF DCG CJ  F  GI
Lsvv b422ovv  XVK edCBG FE  A CB BI BF BI HDBIBJCG  EG HJG GCH EID BAD IE  F   .
Lsvv8 ckwzvo  XKdVYPCAA FH  G CD BE BE  J CFBG GIE  EG DHB CDA BJF  GJ  B  B   .
L cmr1yono1   KWSVedCBH EG  H DC BJ  J  E  GJE BGA  DC  IG  HG  DC DAH CF  B BIA
L43mr g8xoqk1 KXiKM BJE EA  H BJ CJ DA BB EBIDBAGJ  GE EIG EJD GAI DCF CC  C   .
Mr1s2 Lkxny   KMVOM CFE GI  C CI CG CC  G  JJJ CDG  CB BAI BBH BBI DFJ DA  E DAF
Mr1s2 L1y6x   XcP DLEBGBDC  H FH EJ DD  D  JDC CHD  CE BBD BCB  IA  HDBHH BI CBF
M Mk23svvy    KMVOYNCAF FH  I DE DC  J  F  HFG BJC  DC BBH BAH  FB  FI  E  E CEI
Momsv Myyzo1  KWSVBLFECBEA BC EG HF EB BG HAJJCBDA CDF JIHBAIJ EDB GJH GB  J   .
Mrsvs Nk5s2   XcP bPFCGBEG BD HB HA IE  G CGEI HBF  HH DFC DEC CIJ DAD  J  J IBF
Mk1v3yx Ps2u  KMRKM EFHBAB BE EC GD CC BH GFCBBHGH CIBBAAD JHH GBJ DIJ DJ  E IHF
M413 Py1n     XcdVYPCBE FD  C DA CJ CD  C  CCG  FJ   C  DC  DC  CH BAJ  H  D  HA
Mvspp Tyrx2yx KdYbNR BJ  H  A  B  C  B  E   EB  BD   B   D   E   E   A  A  A   .
M Vkx2py1n    KYKUDLFJBBGI BJ IA HC DJ  J EEHIBDAH BBD GDE FGD DBJ  GHBEH  EBCAA
Mro3 Vowyx    KNOdMPEADBAB BC EF FD DJ BC FBFABECJ BGG HEH GGG FCG DBG  G  F GHF
M Wkvnyxkny   XcP YPEAFBAC BI EJ IF CA  G  JFA CDB  CJ  JJ BDI  GE BGB BA  D EBF
M Wk13sxo9    XcN YBCEE FI  J CI CF DF  E BDDF DDD  EJ BGE BHJ BJE BEC BE  C DEA
Mrk1vso Wyy1o KWSVM CDF GB  D CE DJ CB BE DJCGBACJ  DF EEB EAB DDD ECF ED  E   .
M bo8xyvn2    XRYeccDBD HI  G DC EB BC BC DHEC JGI  DF EAJ DCB BHA BAGCAG  H EBH
Mkv bszuox    KLKVccGCHBHH CF JI IB HA  G DCBA JCH BDD FCJ EHC DBD CEAEIC BDBDFA
My18 cx8no1   KMVOYcEBGBBD CE FI GJ BG  B  EBG BBD  CE  FI  GJ  BG CAD HA BA  JA
Mr1s2 czoso1  XMRXDcBFF EE  G CB CD BF BG GGDBBGDE  JI GJI GGB HHH  FD II  D CHF
M gsvuo12yx   KdOhCcCDG FG  A CH BF BB  E BBBF CHA   B BBG  GE  FH BCFBJJ BD CDA
Nk5o Kxno12yx XVK DcCBG FD  B DB BF CC  E  JCG CBA   J BBI  GJ BBE  HDBFC BB CCF
Ny4q Lkuo1    KYKUYP CE  D  A  B  A  C  D  BFJ  CI   A  CA  BC   J  IA  E  A   .
Nyx Lk8vy1    KLYcNRFIFBDJ DB JD JE GC BH HFEGBJIC DBFBBEBBBHJ HCH   A  A  A JFA
N Lsvk1novvy  XWYXM BJB DH  E BC BH BE  E  HHD BGD  BG  GB  HE  FC DJB DI  I   .
Nk18v Ly23yx  KMRKMPBJJ FD  F CJ CC CB  D  FBE BCA   I  FH  EA  DJ BFC  D  F  HF
Nk1xovv Myvo2 KNOdDLFCBBEC CA GH IG EF  E  IBF CAF  CC  JJ BAD  HI BAHCEC CD BAF
Nk5o Myvvsx2  KNOdVPEBJBBD  B EE CH EE BC EEIEBCDB  DC GBC DEE ECC CBB  C  B   .
N Myxmozmsyx  XMSXedDBB IB  D EC DA CG BH ICEHCBJI BAA JFA JAJ GJA BFDCCD BA DCA
N Nk4v3yx     XZRSM BDI DB  I BI CB DI  D  CEE  FD  BC  DD  DC  FF CEE CB  E   .
Ny4q NoMsxmo2 KMKVDLFBCBDB CG GJ JG FC BE FDEHBDJH CCB HBC IBF FEI BBJCBG BC IFA
Nk11ovv O5kx2 KNOdBLFAHBCC CJ HI IF JB BI HHGBBJEH DEHBBHFBBFCBDIA IAIBAI  C FDF
N6sqr3 O5kx2  KLYcbPFCJBDH CG IG JH JH BF GGGBBHIF CJBBAIC JEJ JIJ CIA BA  F JDD
Nkwk2y Qk1msk KdYbCLECEBBJ  G FH EG BD  J DGFBBAEG  DC EGB DAB BBC CCECIG  I IFA
Nkx Qvknnox   XcP MPDFB JH  E FF CJ DJ  E BCFI DFD  BG BJG BBA BBH CCG  H  D CBA
Nkxx8 Rooz    XXiXYPBJF FF  F CE DD DA  I BDBD DDI  CF BEE BEJ BFD  ID  C  B   .
N Roxno12yx   KcOKYPDIIBAD BF FJ EH DJ  G CBHE FFF  IA CIF CHE BIG BIC  J  E DCF
Nyxxso Rsvv   KYKUCDDDJ JG  E DH CJ CD  E BAGE CJA  BB BCD BAI  FF BAECBD  J CHF
Nk5o Usxqwkx  KYKUNRFGBBBI DF HA JE DD BG GGHHBFHF EEC JABBCBA GAI EGD DC  I   .
Nk5o8 Vyzo2   XMRXDYCFF HA  H EJ DF ED BF GDBBBGGB BFEBABJ GAI ICA  FB FE  I EFA
Nyx Wk33sxqv8 KXiKBLGHHCDI DBBBHBBD FD  F CCCD HDH  JD DEJ EAB BHBBDHHBAA  GBJHF
Nk118v Wy3vo8 KUM bPCCH EG  H CD CA BC  F BDCF DCE  EE BFG BFI  GH  JC  C  C   .
Nkvo W41zr8   XKdVMPGBEBGD CJ IJ ID HF BB FABHBDII CGG IBD ICC GBH DAD  G  GBJAA
N6k8xo W41zr8 KYKUMPDCJ ID  J FA DJ FG  J DICI JEI BEF FHF FCI GDF CHG  G  C GAA
Nk5o Zk1uo1   XMSXbPGDHBHE DB IJBBG FG BE GHCHCACE CEH JHIBAJD EJF CHI  J  JBAEC
Nkx Zk204k    KXiKVPCIA IC BG EE EF EH  C  ECI BBD  CF  GB  HA  GD BEI  E  C BBA
N Zy13o1      KdOhMNBFF EB BC CB CJ CC BG FEAJBDDI BIB HEG IAF IHF BGF  J  B CGA
N cmrypsovn   KMKVccEFIBBE BD GH FH EI  E BDFA CJI  CI BGA BCD BCC CEGDIJ BI EHF
Nyx cvk4qr3   KdOhM DBE ID BD DJ EG BG  F BEFH EAF  CI BFG BFJ  HG FDD EA  E EDC
N c31k6lo118  XXiXbPEHFBCD CH HG JD HC  E BIBA EHB BAI CJC DED CGH CCG BA  GBCCA
Nkvo c5o4w    KWSVDLDBH HI  H DF DF DC  B  DBH  HI   H  DF  DF  DC  EFBCC CG  HA
N dk13kl4vv   KcOKbPFBBBDI CF HG JG GB  D  FJC BGE  CI  IH BBA  HB BFH  H  I BEF
Nsmuso dryx   XRYeccCHI GJ  D CE CB CJ  I CAHJ FGF  DC CFI BJC BGC BECCBA BA   .
Noxx8 gkvvsxq XRYeDLDICBBJ BD FE FI DG BC CBDD FJE  EB CIH CJE CCH  FJBFG  J FJF
Nk5o gsxpsovn KXiKbPFGFBEI CE JABAE HH BE HCIHCAID DAFBBDFBCDE HJB CJC  J  FBIGB
Oxy2 Mklovv   XVK BLCHH HB  C CH CJ BE BF FJFCBGEH  GA HFD FJG CFJ DGA DC  F   .
O1sm Nk5s2    XMSXVPEBFBBF CH JH HB GI  D  HBB BIE  EF BFG BBJ  JJ CHE  C  H DAA
Onnso Wsvxo1  XMSXMPECEBBA BF HA EH DG  H CBDA FEE  DI DDF BHE CFI CJC  G  D EJA
Onnso W411k8  KLKVBLEJFBFB BH GB IE HI BA FGCEBGHJ CHF IIEBABF HAJBAEF II BDCEGA
O1xo23 bsvo2  KWSVccFCEBDC  J GJ EH FE  C  JHC CGA  BE BCD  JC  JA CBCDCH CA   .
On bywo1y     KLYcccCDD EJ  C EB CD BI  I BDFA DDG   H BGG BCC BAG BACBDC BA DHF
O1xso grs33   KdYbM DJFBAG BG EI FG DF BA CDAD FHB  IG CGG DCD CEI HAJ EB  H   .
P1on V8xx     KLKVMPDJHBBE CD GH GH FD BD FFIJBGDC CEB JAG JCG HBG CEE  C  E   .
Pvy8n bk8py1n KLKVDLCBA DH  I BF BJ BF  G  JJE CEE  DG BAH BBE  FD  EABBF BF   .
P c34ll2      XVK VPECA JF CD FF FI DH  D  GEG BDJ  DB  HH  HH  GB CAG BA  H   .
P1kxu grs3o   KUM CLFGGBFE CC HG IE ED BE GBAABFID BDB HED GJD DAA DBGEDJ BA HFA
Qoy1qo Lovv   KdYbVPGEBBJI DBBABBAI EB  F CBCJ GBA  JC CJH DBJ BBH CGJ BH BABBHF
Qvoxx L1kqq2  KWSVVPCBF FB  E BJ BI BB  B  CBF  FB   E  BJ  BI  BB BBG  F BC  HA
Qoy1qo L1o33  KUM DLEEBBCI BG HA HD IA BE GGHFCAJF CAJBAHCBAFA GJF  JHCBI BGBFAA
Q1oq L1ymu    XVK BLDCF HG BG DD FC DH  F BFAG DFB  HB BJF CBJ CBE HCG IH  D DIF
Qk18 Mk13o1   XXiXM EJABCF CE IBBAF GC BD GAGDBGEG CHB IEH JJJ GIA IGJ GC  IBJCG
Qvoxx Nk5s2   XRYeBLFHEBFC DB JBBAB GE  D  JIF CGA  FD BEI BHD  JFBCFDBBB BB CBF
Qoy1qo Py23o1 XXiXVPCIE GE BE DA EC CE BI HACDBJCF DEI JIGBCDJ GGG  JG  E  E   .
Qk18 Qko33s   KWSXDLFJGBHB DE JBBAI FC  G CIGC HCI BAH DGB EAB CCE BBIDDE CB JAA
Q1oq Qkqxo    KWSXccEHCBBI BC GD FE DA  E  HJD BIH  BE BAC  IA  FA CCIDHH CG BFF
Q Roxn1smu    KMKVYPCID HH BE EF EH CG BG GIEABJBA CFJ JBFBAGH FEG BEE  G  F HAA
Qvoxx R4llk1n XKdVCLEAI JE  E EC DG GG  J DFHD IGG  FJ ECJ DGF EBA CICEIH BJ FDF
Qk13r Sy1q    KdYbDCDCH IF  D DA EE CA  I CBEA FGI  BG CBG CAI  JD  JBBIF BC DGD
Qk18 Wk33ro62 XMRXVPDHA JG CB EJ EG GA BF GJIGBJHC CDBBAHA JFF JCB BDH  F  J HDD
Q1ksq Xo33vo2 XcN DLDFE HH BG DG FF EB CA IHBGCBHC DIEBBHCBCGHBAFH  IDBHE BG CAA
Qk18 Zo33s2   KMKVMPFDJBDJ  F JD FI GJ  F BEGJ DGJ  BC CEH BCG BJI EGC  J  H EAA
Qk18 bon42    XZRSVPDEA IE BB GC DD EH  F BFBG DHG  EC CIE BEB CBJ BIF  I  E EAA
Q dowzvo3yx   XcN ccFBABCG  C EC EE DF BB FFGCBFHI  EE HAD FBJ CFG CAHDFI CA HDI
Qy1wkx drywk2 KcOKNRDBF FJ BG EF DG FI BD EGHHBAFB CGI GIB HIC GJH   A  A  A   .
Q1oq gkvuo1   KMRKBLCIC HI BD DH FB CJ  F BGEJ EFD  HD CBB CIA BDI GHA FH  F FAA
Qk18 gk1n     KdOhVPDIABCA  F FE FB DB  I DBBI JAA  JC EEE EBJ CEA CDH  I  B GAA
Qvoxx gsv2yx  XZRSbPFIEBFI BF HA IE EC  F CDFI GDG  FI CGF DBG BDE DDB CA  E GGD
Rk1yvn Lksxo2 KMRKbPFHABGJ CB HC II DI  H DHFEBAHH BEA EJC FIJ CGD CJF BF  F JFA
R4lso L1yyu2  XWYXccDAGBAE BE FA FI CF  H CJFE ICC  FF DBD DHH BIH BBGCCC BF HFA
R Tyrx2yx     XXiXDcCCA FE BA DA DJ DB  F BBIF CJJ  EA BEF BFE BCI  FABDG CA CJI
Rkv Wmbko     KUM NRCHI HA  H CC DH BI BI HBIGCAIB BJA JDFBAII GED   A  A  A DCF
R bo8xyvn2    KcOKCLEEF JJ  B EG CE CJ  E  GBI BCJ   B  HC  DB  EI CHIEBF BG  II
Rk118 czsvwkx XcP BLBED DJ  F BI DA BF  J  GDJ BFB  BG  IA  JH  GB BDI BF  B BHF
R gsxxsxqrkw  XWYXYPBIF EA  E CD BB BI  D  FCE BCF   H  FI  DH  EH  JH  C  C  JA
T Lk1psovn    KdYbbPFIJBHA EABAHBAI GJ  G CDCF GDE BCI DHB DHG CDI DGI CA  DBCDI
T4kx Loxs04o9 KLKVedDEDBAD  G EI DG EA BF EDDIBBJD  HA FIB ECB DCF CBB FG BD EDA
T4kx Lyxsvvk  KLKVCLCIE GJ  B DD BI CF  F BEAH DGB   G BDJ  JI BBB BCCBEA  F   .
T Mkxqovy2s   KMRKVPEDIBAD  C GF DC HB  C  EEA BAD   C  GH  DC  HB CHG  H  J BAA
Ty2o Mkx2omy  KYKUVPGAABEE DD IFBBH GF  C  GJG BHD  DI BAB BDA  GJ DBJ  E BE BGF
Tyo Mk13o1    KMVObPGGDCAA CJBAIBCB DC  E BEEH EAE  FH CBA CCC  GI CEB  I  G CFA
Tkmu Mvk1u    XcdVBLCDC FF  J DE CD EF BC EEAFBCBD BJE HAC HAF GCF GCD DF  DBDAA
Ty2o M149     XRYeVPEHJBDD BA EI HC FF BH HEHCCBEH BFD JIABADC IFE CDH  F  E HHD
T4vsy M149    KMRKCLCAJ EF  A DI BJ EC BA DIFJ JBG  CD FFH CHJ EHI BDCCAF  F   .
Tyn8 Nk5s2    XMRXM FCIBDC CB GB HE EB  G CGEB GHB  JH CHD DID CCG IIFBAF  IBAAI
Tsw N68o1     KLKVNYBGA DJ  I BI DB CC BE CBCI FED  FG DAE CGI CJI  DD  D  A CHF
T4vsy P1kxmy  KMVOccFJJBID BA IA HE DC  F CEIC HBF  CH DDA DCG BFI CDBDHE BI HHF
Tsw Qkx3xo1   KWSVCLEJHBDG  H FI DI CG BB DIHBBAGG  EA EFA DGH CEB DAEDEH BA IFA
Tyrxx8 Q14ll  KNOdNRCBA HA BD DC FB CI BF EAEABBDA  JH FEE EGC FFB   A  A  A DGF
T Rks123yx    KMRKedCCF GB  F DC CG CG BB BFGI EAI  CF CAC BIF CFH BDC  J  A   .
Tkmu Ry6ovv   KMKVDLBFB EB  E CG CB BJ  C  CII  GI   J  EF  DJ  DF  CI FG  C  JF
Tyrx U14u     XcN VPCHI IG  E DD DI EF  B  CHI  IG   E  DD  DI  EF BAC  E  C BBA
T Voyxk1n     XcP VPDEB JF  G EI EC CA BA CJGE IAI  IB DHJ ECI CCB BFI  E  F BAA
Tsw Wy11s2yx  XZSdDLFDHBEH CD FI II EH BA CHEE HDA  JH DAC DFB BHE  JCCFH CA CHI
Tyrx Wy2o2    KcOKMPDJJBAC  D FG DE DE  F  GHA BGH   E  IJ  EI  FE CBB  J  D  IA
T W4wzr1o8    XMRXYPDAJ JE  F DH DC CG BD EGBIBDDA  FH GBG FCC EDG BGB  D  D GAA
Tyo Y124vku   XZSdbPEABBAA  C GA BJ CI  E  IHG CDI   C BCG  EE  FF BJD BB  E   .
Ty1qo Y13k    KUM NRDDG JD  J DF EG CD BF FHHJBGBA BCI HDA HEB EJH   A  A  A   .
Tsw Z1o2vo8   KcOKDLGBGBGD CH IDBAH DC  D BEDH DHH  GF BIB CCH  IC BBADAI BF CAA
Tkwso a4s1u   KUM McCBJ EH  I CE CG BH BC BBII CIG  CD BAA BCF  GD CGA FI  E   .
Tyrxx8 bk8    XZSdCLFHJBHE  H GH HI FI  G DAFD IIA  DC DGG DDH CBI CIAEHJ  F GFH
Topp boon     KWSXM BGF DJ  C BD  J BG  D  BJG  EE   C  BI  BA  BI DDC BJ  C  HF
Tsw bsmo      KLYcVPGBICAA CA JIBBA GC BD HBCHCBGD DFBBBAEBCIJ FGE DDA BG  ICEBD
To118 by823o1 XcN edCFH GG  F DB CG DC BE DJBA JHJ  DD FBI DCE DIC  IHBGG BE CFA
Tyrx b422ovv  XZRSM DBF HG BD DF GA CF  D  GDA BFB  CE  GI  JE  FF EJI DJ BD BFF
T4kx ckw4ov   XZRSCLFJBBFH BG JA HI CG  E CACA FEB  FC DBA CCG  JB CJAEEA CF GEA
Tyrx crovl8   KLKVYPEAE JC BB FE EJ BI  G BDFE DCF  DA BII BDF  GD CCC  F  F DAA
Tyov cusxxo1  KMRKM DBF HD  F CD DH BG  E  EFA BAI   G  DI  EG  CI CCH BF  D BBA
Topp c3yxo    XZRSYPCEJ GJ  G DC BJ CA  E  HAC CAJ  BA  JH  EI  EE BAD  I  C   .
Tsw c4xnlo1q  KUM M ECJ JB BC EB EC FH BD FFJABDJH  ID FHI FHJ GEE GIG EG  E ICF
Tsw d1klo1    KLKVedCBC FE BD CI EE BI  C  CDD  FJ  BD  DB  EG  CA CED CD  F   .
Ty2o e1slo    XcP ccEFDBAB  D EG ED GB  D  JEI CBI   G  JG  HC  JB CEJEEE BG BJF
To118 gsvvk1n KYKUM BGB ED  E BH CG CC  D  HAH BHJ  CB  HH  JJ  HG DAA BC  C   .
T iy4xqlvyyn  XcP YPBIE EH  F CA CI BI BB DDCH IJA  HE EBJ DIC DAE  EJ  C  A EFA
Uo5sx Lk22    XRYebPFJBBIE CA ID HJ DI  F BGIJ EGC  EA CBJ BJF  IC DAD BC  F GDA
Ukv Nkxsov2   XMSXYPBIB FI  G DE CD CC  B  BIB  FI   G  DE  CD  CC  II  A  D  IH
Us1u Qsl2yx   KNOdbPEEBBBI CI IE IG GI  I CHCD HFA BCG EDD ECA DAJ BJA  C  CBDAA
Uox Q1sppo8   KXiKYPEJABFA CB GJ FI DF BE GBCGBIDJ BCB JID HAH GAA  JG  F  DBAAA
U Ro1xkxno9   XXiXBLFFBBHB BD JE ID JE BD GAJABIEA BCI JGJ JAA JBHBBJJBEJ  FBIAA
Uox3 R1lou    KWSXBLFFABEH CJ IF JB HB  G CIBG IBF BBH EAF EHE DBJBCBIBAE BABDBA
Uox Vkxn1ok47 XVK YPCID HE  E DE CJ CC BA DJBJBAGC  IF FAF EFG CID BEF  F  H HDI
U Wmbo8xyvn2  XcN MPFGABGB CG IJ JG GG  E BHIJ EHA  GF CDD CGA BFF DDC  J  I GCF
U Ws3mrovv    XXiXYcDCI JB BC FB ED DD  C  DEC  JE  BC  FB  EE  DD BEF FJ  I BCF
U Wy1ovkxn    XMRXbPFIGBFJ BC HC HJ FD  J DAIC IIA  ID DGD EHH CJF BIB BD  EBAED
Uox Ylo1upovv XKdVDLFADBDG  F GC EI ID BA DECD JHA  CA EAI DAD EBE  GFCFI  I HCF
Uox Zrovz2    KcOKNRDEE IF CE GJ GE II  H  JBB CBE  GE BFA BFG BIH   A  A  A DAA
Us1l8 Z4muo33 KWSXMPGIACCD DBBBJ JG DE  D BJCI FIH  DF CGC CAB  JB ECJ  I  G DGF
U c3svv6ovv   XMSXccCHJ GE  A DB CG DA  B  CHJ  GE   A  DB  CG  DA BAHCAF BG  HF
Voyx N41rkw   XMRXBLEIEBCH CA GG GF GH  H DAAG IEE BBG EDG EFI DHHBCDB IA  HBBID
Vox N8u231k   XXiXMPEDBBCH  I HH EF FI  C  GGH BIH   J BBH  GE  II CID  I  D CAD
Vk118 Ro1xnyx KNOdYPCID HA  I DD DH CH BC EEHJBCCC  JE FFH EID DAH BFG  C  C CCF
Voo Vkm8      KLKVbPEJBBEB BB HH EH DH BF ECJBBCEA  IE GBF EDA DEA CDJ  I  C FCF
Vox Wk3429ou  XVK YBBJJ FC  J CG CI CB  G  IAF BJB  DA BBD BBJ  IH CDF CC  F CGF
Vvy8n Wy2ol8  KdYbMPFIJBEJ CB IJ IG GE  H DFFI JCI BAC FBD EHB DFB DHB  G  G HII
Vkxmo Zk11s2r KNOdM DCH IE CC FD GC DI BA ECHDBBCD CBC FHH HAA DDE EID EI  G IAA
Vk118 Zk11s2r KdOhNREGEBCI CI GH JE FC BD FICJBFFC CBA HEA IEA EFC   A  A  A FII
V4s2 bs5o1k   XWYXccBGG DE  A CA BD BH  B  BGG  DE   A  CA  BD  BH  GEBBJ  J   .
Vk118 croo32  KLKVNRDDI JC BI EC GA CB  D  GIC BIF  DG  II BBC  FA   A  A  A BEF
Vyxxso cws3r  KUM VPFAIBEG  I IA EE EG  J DBEI JBF  EB FHB CIJ DCG CEF  F  J   .
Vy4 grs3kuo1  KNOdCLFIEBFH CA JF HD GD BA EHAEBDCA  JD HCE FCC FHG CHGECB BB ECA
Wsuo Kvn1o3o  XcP BYCBG FE  C CH CF DD  B  CBG  FE   C  CH  CF  DD DBH DG  B  HF
Wk138 Lk11o33 KLYcCLGCFBHJ  E JE GA GF  F BGJG EHG  BC CBG BGD BGG DADEFA BE FHF
Wsuo L1y6x    XZSdYPCED FD  E BI CG CH  E  IFD CCI  CD BAB BBA  HG BAH  D  D   .
Wsuo Nk5s2    KYKUbPEIJBDB BJ HH FF DE  H CAFB FEJ  GC DAA CGD BFD DBA  J  J HIA
Wsuo Nsk9     XZSdYBCAJ FG BC CC DG BJ  C  CBG  FI  BC  CE  DH  BJ CAB  G  D  JA
W N4xmkx      XVK ccEAH JD  I EH DA DA  C  JGJ CDA  BE BCB  GJ  GI BHCDBH CF BFA
Wsuo Ok2vo1   KXiKNREJABEI BE GE HI EJ BD DEAABAAA BBD EEF EJB DAB   A  A  A HAA
W Ps39qo1kvn  XWYXM CAJ FJ  G CA DH CH  E  IIE CAJ  BE  GG BAG  JC EBF DF  D   .
Wov Rkvv      KMVOVPEECBDB BI GI HH DD  G BEBG DJI  EH CBA CAD BDG CDD  H  H FFA
W Rk3mro1     KWSXedDBH II  D EA DC BJ  I CFED HBF  CI CGJ CHA BBI CCA BG  E   .
Wsuo Rok3r    XcdVM CII GF  I DA DG CH  J CIBF GJI  FF DBF DCF BIJ CFJ DA BA GFA
Wsuo Usxqo18  KUM YPCAJ FE  D CF BE BC  B  CAJ  FE   D  CF  BE  BC BAC  G  D  GI
W Vkfkvvso1o  XcdVM DAD HB  D BI DA DG  D  DEE  HG   D  CA  DG  EF EGI EH  G BAA
Wsuo Wk12rkvv XVK bPDDA HH BJ EH FD CH  G BJCI FBG  JA CEH CII BGB BEJ  I  G GHA
W Zkqvsk14vy  KXiKDLFAEBCA CI HB HB FE  D BAIF CFJ  FE BFA BGH BBE BADCID BJ BHF
Wk1u ckvk2    KWSXM CFI GA  I CI DD BI  D  GDI BHA  BH  IA  HF  DG DFI DC  I BDH
Wsuo cmrwsn3  XZRSDL CA  B  A  A  A  A  C   EB   J   C   G   H   E  HICCA  GCBCH
Wsuo cmsy2msk XVK M DHE JE  F DG CG GC  H BJGI FBJ  CG BIB BJJ CII HFG GE BF IHF
W do33vo3yx   KYKUM CBB ED BA CG DF DJ  D  EJI BBG  BE  FJ  FF  HI EGD DC  I BCA
Wsv3 drywz2yx XZRSMPCJJ HF  G DI CD CG  D  FIA BGA   I  HB  DD  EE CBC  B  C BEA
Ws3mr gol23o1 XWYXMPFHGBGH  I IJ EJ FH  E  ICC CDC  BJ BDC  ID  HJ DCF BC  I CBA
Wyyuso gsv2yx XXiXYPDIBBBA  J GB EF DC  H DABF IDE  EA EFB CEJ BGI CCI  H  F IAA
Wk15ovv g8xxo XcN YPCII HG  H DE DH BF  E BGEE EAI  BG BJI BCA BBD CAD  D  D CEA
Wsuo iy4xq    KLKVVPDGJ JD  J ED EC EJ  F BCFI DCD  FE BIB BHH BFH BEJ  B  G DFA
Xsmu O2k2u8   XMSXBLDDA HG BC DF EB EH  E BDGH DCG  FF BGH BJI BGH FBC DA  F   .
Y99so Q4svvox KMRKccFEHBDH  C FI EH BC  C BADI CHB   D BCJ  IA  CE CGBEFJ CC BHF
Y WmNy6ovv    KdOhMPFHCBFC BIBAF EJ GF  C  JHI CEJ  DG BGI  JB BAB DCF BD  D CAA
Ywk1 Wy1oxy   XKdVbPDFJ IE  E EG CH CB BC EJJCBCFH  DH GJJ DIG DIH BFB  I  F   .
Y99so cws3r   XcdVccFBEBEE  A GH FE HJ  J EHDJBBGJ  BD FID DHE FCI CCJEFD BFBJEA
Y99so fs1qsv  XKdVM DFJ IA BF EF EI GD  H BEJD DFJ  GB BHG CAC BHF GIC JD BD HAA
Zrsv L1knvo8  KcOKVPFCGBGD BC II FA HH  E BFFG EHA  DI CEF BGH BHE CFA BB  B HFA
Zrsv Qk1xo1   XRYeDLDBD ID  J ED EB DA BE FIIFBFED BAE HFB HBE FDF  FIBEB CD EFA
Z Sxmk5sqvsk  KdOhbPFEABDF DA IC II FF  B  FEA BDF  DA  IC  II  FF BFH  G BE BHC
Zk4v Wyvs3y1  KWSVDLEDHBCD  J GC FF EA  J EBDJBCAD  HJ GHG DJA DGE  ICBHA BFBCGA
Zo3o Y'L1sox  KdOhBLFFBBGA CD IG JA IH  F CCDF GAC  HF CHI DCI CHDBCCEBBF BB   .
Zo3o by2o     XMSXBLCDH FC  A BF CF DA CEBEAFDECFG BGACBGFBDBEBFGG FCD ED  G HFA
Zk3 cro1snkx  KNOdYPCDG FG  G EB BJ CB  F BCFH DCJ  CE BGG BCF BAF BHC  B  E BJA
Zk3 dklvo1    KMVOBLEHDBFE  G GB EI CJ  G BJGG FGG  CJ CFA CFC BHI IEG IE  J FIA
b Lovvsk1n    XZSdccDAJ HC  A DD DB CG  F  DFE  IC   A  EB  DC  CG BBHCGJ BC BDA
bsmu L41vo2yx KMKVedCHB HH  F DF CJ DD BC EJDDBDFI  EI GDA EDF EAD  GC JA  D EFA
bkxn8 L42r    KWSXVPDFH JG  H FA EF DJ  F BDJE DEE  ED BHI BJC BDG BGH  C  E DAA
bsmu Mo1yxo   KWSVM CBG FG  E CC BI BF BC CHJG GGF  ED CGG DAE BJI DJB EE  E CFA
byx Mo8       XMRXDLCFG HA BD EC DG EE BG HAFIBIEF DBC JGFBBCI JJA  EBBBI  IBAFA
byl Noo1      KWSVbPEGGBAI DD HF IG HC  D  GFC BEC  EE BAC BAJ BAC CIG  I  I CBF
bsmu Nowz2o8  KLKVM DCH GI BD EC CJ EF BI DJEJ JDJ  HI EDI DIA EGG GFJ FD  H EAA
bsmr Qonwkx   KLYcM EGCBBJ BG EJ GF DH  H CBDB FID  GJ CEE CII BFA IGG GF  G   .
byx Rk22o8    KXiKM DEBBBA  J EF EJ EG  J CDDB GFI  FA CEJ DCC CHE CFB  J  E FGA
b Roxno12yx   KXiKMPGAIBGA CIBDA HE IJ  I EAHBBBIC BAD IGC EBH HAI ECG  E  GBGHA
b Tkmu2yx     KMKVNREBJBAB BI GF FI JC CA JFCICFBA FEIBFAJBGFJBDEC   A  A  A EII
bsmu8 Tyxo2   KMKVbP DD  G  A  C  E  H  B   DD   G   A   C   E   H CAF  F  E   .
byx Us33vo    KMRKNRDHG IC CB EC GA DF  F BHHA EAI BBF CDI CJJ BFH   A  A  A ECF
bk8 Uxsqr3    XXiXDLEIGBEF BB FB HG EA BB DJGHBBAC  GH EBA EJH CIE  IICAE BG FAA
bkxn8 U43mro1 XcP YPBIG EE  H CI BG BB  B  BIG  EE   H  CI  BG  BB  JJ  D  B   .
b4n8 Vk6      KUM YPDAH IA  B EC DG CJ  H CECB GFG  BI DHJ BJI BIE BEF  C  C   .
bsmu Vokmr    KdYbNYCEG HG  F DF DJ BD  G  JBC CDE  BC BAC  JG  IA  EE  A  B CFA
bsmu Wkxxsxq  KWSVYPCAF FC  I DB CH BH BC FBDEBDCD  FG GED EEF EFJ BFF  D  C EAA
b W4vvsxsu2   KdYbDLDEI JA BB FA EF ED BA CCII GBE  ED CJF CHD CGJ  GABHG  G EFA
byx Yo23o1    XMSXCLFCDBDF  I FC EE FC  J DDGI IJF  DJ DHH CIE CJG DGHEHF BJ HFA
bo8 a4sxyxo2  KLYcccDBC GI  C DC CC CE  B  DBC  GI   C  DC  CC  CE  IGBFA BF  HA
b bkws1o9     XKdVcDEJGBBJ  I FH DD CB  H DDFI IIC  DG DGF CIA BGF BFFDHB CJ IHF
byxx bo8xyvn2 XZSdVPBCG CH  D  I BA  F  E  CDJ  EJ   D  BG  BD  BE BJA  C  J BJA
byx byoxsmuo  XZRSYPCHF GI  F EC EC GB  G  JGB CDI  BG BCI BAE BHC BIB  D  C BJB
b8xo ckxnlo1q XMRXCLGCHBHI BE GI HG EG  G DBEG JAC  HE EJE DEF CEC DAJEJC  F HEA
b ckx3kxk     XXiXccDJE IG  B DI CI DG  E BAIJ CGH   D  JE  HB  HG CADDGJ BG CFA
bsmu cmr4     XZRSDLCAI FH  I DC CF BI  D  GFD BHA  BH  JI  FE  GC  EC JE BD BEA
b4lox cso11k  KdOhYPDICBAB BG FA FF CC  B  DIC BAB  BG  FA  FF  CC CAA  H  G  JI
by8 cwkvvo8   KWSXNREFJBBD CA FJ FH GI BC FDEIBDGJ BFF HBD GGA HDF   A  A  A HEA
b drywz2yx    XcP CLFEJBEJ  H HD EH EC  B  FEJ BEJ   H  HD  EH  EC CFFEFA BH BEA
byl gsvpyxq   KMKVCLCII GD  D CF DD BG BA CGIC GGH  DI DBF CFJ CAE BDFCFH  H DEC
b gsvvskw2    XVK MPDAD IE  E DF DC CD  C  DBC  IH   E  DJ  DC  CD BHJ  F  D   .
bylsx iy4x3   KWSVMPFCCBGD  J IC EG GC BD HADHCABJ BFDBAED ICH FDF DFC  J  BBAAA
c3o5o Lkvlyxs KUM BLFBCBBH CJ FE II ED  G BHFA EBC BAA CAE CHG BFFBCDG JI BI BAA
cmy33 L1knvo8 KcOKM CCA GG  F CA CI BD  D  CJA  IA   F  CH  DB  BF CIB CB  D  JA
csn L1okw     XZSdBLFCCBEA BG HD HH GA  E  HDA BIF  CC  JD BAG  IGBDCABGG BH CAA
c L4omrovo    KdOhDLEGBBBC BI FE FE DF  C  GIA BGA  CE  HG  HF  EJ BBBCCG BB BDF
c N4x23yx     XMRXccFIBBEF BH GG GI CB  C  IDB CBA  CB BAG  IG  EA DCAEGF DC BFF
c Pvo3mro1    KdOhccFDABFJ  D IC FA EH  G BGBJ ECG  BB CBI BEJ BGD BJGDFE BF EHF
c3o5o Qk15o8  XcN BLFFHBEC CB FI IB CD BI IHFJCFID CHBBBDIBCJJ EHIBBGA FD  HBEFA
c3o5o Tov39   XZRSccEDJ JG  A EE DG GF  E  HBB BEI   B  GI  FG  JJ CCJEAG CC BFA
c Vywlk1ny99s KWSXCLEFDBAD  I FD DD FC  C  FAH BCD   I  GD  DJ  FI CIJEAH  G BAF
czsuo Y6ox    KcOKccFCIBCC  B GH EF FB  E BHBG EAD  BC CBB BEG BFF CAJDHC BH DFA
c3o5o ck7     XVK CLGDDCBA  G JB FG FJ  G DAHA IHC  BJ ECA CDA CHE DGHEDC BG  JA
dyx8 K1wk2    KLYcMP BG  C  A  B  A  A  C   CI   E   A   B   A   A CEH  E  I   .
d Lo1xk9k1n   KMVOCLFGCBGJ BH II HD FD  I DBIB IEB  GB EFA DEC DHD DFBEEC BH FDA
dyw L1yyuox2  KNOdedCIB HG  D EC CF CA  I CGFI GFH  EI DCE DAA BHJ BAGBEE  H DEC
dyw L14xkx2u8 KWSXbPFJDBFC CD GJ HF FD  G CHGF GIG BDD DGJ DIE DCB DBF BA  G JEA
d Po1xkxno9   KdYbccGIHCBD BA JB GF CH  E BFBI EEI  BF BJG BDH  IJ CJEEEF BD DFA
dsw Pvkxxo18  XcN CLDGIBAD  D EI CI FE  I BIJH EJD   J CAH BGC BJI CAJCEG  D DCH
dyw Pyvo8     XWYXedCGD HA  B CG CD DA  E  III CCA   J  ID  IC  IG  IBBEH  E CFA
dyx8 Q68xx    XcN bPGECCBB BEBAH FJ FC  F CDGE HHA  CH DFC CDA BJD DDH BJ  E HEA
do118 Rk1zo1  XKdVYPCGF GI  I CG DA CJ  H BDDH DDJ  DC BDF BGD BCI  JC  F  D ECF
dyl8 Rk11kr   KdOhCLCIJ GD  H DG EB EE BH HEACBJFE BJFBBBF JBJBBFD BGGCBB  H   .
dyww8 Ro11    XcdVCLFFJBEB  C EI GB HD  I DBGC IHE  BG ECB DEJ DFJ DFCEBE  J JCF
dsw R4vo33    KMRKDLFCABCA BH FD EE CB  E  JCH CCH  CC BAG  IA  FC  HABEE BB BIF
do118 Uoxxon8 XcN M  BJ  E  B  C  D  B  B   BJ   E   B   C   D   B GJC HA  I JCA
ds3y Vkxn14w  XcdVYPCAF ED  C CE BH CA  H  IFE CBJ  BC BAF  JJ  HB BDB  G  B CIH
dsw Vk4nxo1   KWSXM BJD EH BA CB CJ CE  G BBDG CFG  EC BCJ BDJ BAG CJJ BD  F CEF
dyw Y'Wkvvo8  KLKVDLBIB EG  B BJ BI BH  F  JDH CDI   J  II  JF BAE  DH JI  J   .
dyw Zkmsy1ou  KdOhedCBD GB  E BH CC  D BH EAGBBBEF  ID EII EJB CEE BHI EF  E CDF
dyx8 Zoxk     XZSdM FBABEH BA FG FC FD  H CIHC ICB  GD DAH DEA BHE IBA JJ BIBBFA
d Zoxnvo3yx   XcdVDLFHIBDI  B FG FJ DE  D BDJJ DFH   H BEJ BGB  IH BDDDHB CA BGA
dyx8 Zo1o9    XMSXBLCAA FB  C BE CJ CF CD JHHICHDC DHJBCHCBGFC JCF DJI CJ  H   .
dyx8 Zrsvvsz2 KYKUCLEEBBBD  F HG FC HG  F BFEG DJH  BH CCG BEJ BJB BGACJA BB ECF
do118 Z4rv    XRYeYPBHC EC  D BH BE BF BA EAIGBBFA  FH FHJ DGD EAG  GF  A  A JAA
dsw bksxo2    XWYXVPFIABJE  J JB GC HI  I DDHCBACI  EI GAE DBE EGJ CHA BD  G   .
don cswwyx2   XKdVedBCH DC  E BE CF BC BJ IDJGCEAC CECBAEIBDEI IBJ BGH BI  G FAA
dsw do4pov    XXiXCLCHJ GJ  E DF DB DC  E BDFJ DFF  DB BIA BEI BFI BDDBHD  J CHI
dsw gkvvkmr   XWYXDLEIABBC BI FA HB EE  H DADB HHB BBA DDI EAG CDJ  JECHA BG HFA
fsxmo Myvowkx XcdVVPGAABDJ  A JE CJ GA  C BCDG DAJ   B CAB  GJ BBA DAA BC  J BGA
fyx Rk8o2     XZRSBLGBABIG BJBAH JI HE  G CHCI HFD  GJ DJJ DGG CIGBBIC JG BDBDAA
fkxmo Vk6     XWYXCLDGA IB  F DH EE DH  H CCGI FGG  EB CHJ CFH CEG BHACIE  D FCF
gkvv8 Lkmuwkx XXiXCLDIHBCE  B GH CH DG  H BHHF FAG   G CHC BCF BJE BIGCJA BH FFA
gkno Lyqq2    KLYcDLFIACAH  IBAH HBBAF  F CHHI JHI  DC EHE DCC EBH BCBCGH BJBGAA
gsvv Mvk1u    XcP BLEAIBBH BB GG EB DE  B  EAI BBH  BB  GG  EB  DE JEC HC BB BCA
gkvv8 Ty8xo1  KMKVBLFJDBHC CC ICBAA FH  B  FJD BHC  CC  IC BAA  FHBCCCBDJ BF BGF
g U1oxmrsmus  XWYXBDCCB FD  C CB CD CC  I BAGD CID  BF BAH BCE BAG DCF FI  G   .
gsvvso WmQoo  XcdVMPEJHBCH  H GF EI DH  F CHAD IAG  DC DHJ DBB BDI DCF  J  D HAA
g bkxnyvzr    KXiKCLEJCBDG  F HG FA JE BC FFBBBFBB  DJ IJH EFB IHF DBDDIB CA IHF
g dyvvo2yx    KMRKDLEHFBCG  D GB ED FC  G BHAA EDD   H CBH  JD BEG  DHBBD  H DIF
gsvvso ez2rk6 KdYbBLFHDBEE  J IF GA HI  I DBJI IFH  JH EHA ECA DDCBDBEBDB BC JGA
gsvvso gsv2yx KUM MPGDBBHA  J HH EE DB BB EJAIBEFH  DA HHF DFH CEJ EAI  E  DBAAA
;
