### Wkuopsvo - py1 mywzsvon o-vs2z yp Occ ns231sl43syx.
###

## Lopy1o wkusxq mrkxqo2 ro1o, zvok2o 3kuo k vyyu k3 Wkuomyxp
sxmv4no ../Wkuomyxp

## Py1 xy6ol o731km3syx yp myno kxn nym4wox3k3syx.

XYdKXQVO=xy3kxqvo -V
#XYdKXQVO=xy3kxqvo py1 xy sxno7sxq.
XYgOKfO=xy6ok5o

## cePPShOc k1o sx ../Wkuomyxp :
.x6.r3wv: ;     $(XYgOKfO) -psv3o1 vCr -sxno7 -r3wv $*.x6 > $*.r3wv
.x6.3o7: ;      $(XYgOKfO) -sxno7 -novk8 $*.x6 | mzsp $*.3o7
.x6.ov:  ;      $(XYdKXQVO) -b$*.ov | mzsp $*.ov
##.x6.m:  ;       $(XYdKXQVO) -b$*.m | mzsp $*.m
##.x6.r:  ;       $(XYdKXQVO) -b$*.r | mzsp $*.r
.3o7.n5s: ;     vk3o7 '\2m1yvvwyno \sxz43 '"$*"; 6rsvo q1oz -2 'bo14x 3y qo3 m1y22-1opo1oxmo2 1sqr3' $*.vyq; ny vk3o7 '\2m1yvvwyno \sxz43 '"$*"; nyxo

# rk5o 3y z1ovykn 3ro psvo2 3rk3 myx3ksx wkm1y nopsxs3syx2 y1 3ro
# l83o mywzsvo1 6svv mywzsvo o5o183rsxq 3rk3 1opo1oxmo2 3row
# sxmy11om3v8.  kv2y z1ovykn k psvo 3rk3 2o32 l83o mywzsvo1 yz3syx2.
ZbOVYKNc = -v ./o22-mywz.ov


## psvo2 3rk3 myx3ksx uo8 wkm1y nopsxs3syx2.  kvwy23 o5o183rsxq
## nozoxn2 yx 3row lomk42o 3ro l83o-mywzsvo1 sxvsxo2 wkm1y o7zkx2syx2.
## o5o183rsxq kv2y nozoxn2 yx 3ro l83o mywzsvo1 yz3syx2 psvo 2sxmo
## 3rs2 wsqr3 ny ynn 3rsxq2 vsuo 341x ypp mo13ksx mywzsvo1
## yz3sws9k3syx2.  grox 3ro2o mrkxqo, bOMYWZSVO.
MYbO = o22.ovm o22-2s3o.ovm

### O5o183rsxq l43 o22-nol4q.ov, o22-sx23kvv.ov
###		  o22-2oxn.ov , o22-2oxnC.ov
### NOZbOMKdON:  o22v-l4q.ov
##
OVM = $(MYbO) o22-mywz.ovm o22-m423yw.ovm \
	o22-nno.ovm o22-mywzk3.ovm o22-pyx3-vymu.ovm \
	o22-rovz.ovm o22-sxp.ovm o22-wyno.ovm \
	o22-wox4.ovm o22-wy42o.ovm wy42owo.ovm \
	o22-265.ovm o22-3yyvlk1.ovm \
	o22-31x2.ovm o22-43sv2.ovm \
	o22n-ov2.ovm \
	o22-v2z-v.ovm o22-7v2-n.ovm o22-523-n.ovm o22-k1m-n.ovm \
	o22-2k2-v.ovm o22-2k2-n.ovm o22-2k2-k.ovm \
	o22-23k-v.ovm o22-23k-n.ovm wkuo-1oqo7z.ovm \
	o22-ywq-v.ovm o22-ywq-n.ovm \
	o22-l4q2-v.ovm o22-l4q2-n.ovm o22-tkq2-n.ovm \
	o22-xy6ol.ovm xy6ol-wyno.ovm xy6ol-pyx3-vymu-wyno.ovm \
	o22-ovnym.ovm o22-1y78.ovm o22-143sv2.ovm \
	o22-2-v.ovm o22-2D-n.ovm o22-2E-n.ovm \
	o22-2zD-n.ovm o22-2zE-n.ovm o22-2zF-n.ovm o22-2zG-n.ovm \
	o22-1-n.ovm o22-1ns1on.ovm o22-1-k1q2.ovm o22-1-n.ovm o22-1n.ovm \
	o22-2zG6-n.ovm w2ny2.ovm
##      ^^^^^^^^^^^^^^^^^^^^^^^ gsxny62 yxv8 (l43 lo zvk3py1w-ylvs5sy42)

### dk1qo32

kvv: $(OVM)

sx23kvv: $(OVM)
	-$(SXcdKVVNSb) $(VScZNSb)
	$(SXcdKVV) MrkxqoVyq *.ovm $(VScZNSb)
	o7zy13 T; py1 S sx *.ovm; ny T=$$S; $(SXcdKVV) `lk2oxkwo $$T .ovm`.ov $(VScZNSb); nyxo
#	3o23 "$(VScZNSb)" = "." || $(SXcdKVV) *.ovm $(VScZNSb)

ns23: o22-m423yw.ov
	@3y4mr ns23
## 25x mywws33sxq rkzzox2 sx ../Wkuopsvo

mvokx:
	1w -p $(OVM) \
	o22-m423.ovm o22-owm2.ovm o22v-l4q.ovm \
	o22v-2k2.ovm o22n-2k2.ovm o22k-2k2.ovm \
	o22v-l4q2.ovm o22n-l4q2.ovm o22n-tkq2.ovm \
	o22v-23k.ovm o22n-23k.ovm \
	o22v-2.ovm o22n-2D.ovm o22n-2E.ovm \
	o22n-2zD.ovm o22n-2zE.ovm o22n-2zF.ovm o22n-2zG.ovm \
	o22n-1.ovm o22n-1-k1q2.ovm o22k-1.ovm o22nn1.ovm \
	o22n-2zG6.ovm \
	o22n-k1m.ovm o22n-ywq.ovm o22n-523.ovm o22n-7v2.ovm o22v-v2z.ovm o22v-ywq.ovm o22-wy42.ovm

ns23mvokx: mvokx
# kxn zy3ox3skvv8 wy1o


### dk1qo32 lovy6 ro1o k1o yxv8 py1 no5ovyzo12 - kxn 3ro2o w423 rk5o zo1v

### bozvkmo fo12syx x4wlo12 (k2 sx ../nym/Wkuopsvo !):
o22-m423yw.ov: ../fObcSYX
	zo1v -zs -o '2/".*"/"$(OccfObcSYX)"/ sp /o22-5o12syx/' $@


### Psvo Nozoxnoxmso2

.ov.ovm:
	$(OWKMcLKdMR) $(ZbOVYKNc) -p lk3mr-l83o-mywzsvo $<


o22-m423yw.ovm: o22-m423yw.ov o22-mywz.ov
	$(OWKMcLKdMR) $(ZbOVYKNc) -p lk3mr-l83o-mywzsvo o22-m423yw.ov

o22.ovm: o22.ov o22-mywz.ov o22-m423yw.ovm
	$(OWKMcLKdMR) $(ZbOVYKNc) -v o22-m423yw.ovm -p lk3mr-l83o-mywzsvo o22.ov

o22-2s3o.ovm: o22-2s3o.ov o22.ovm

o22-sxp.ovm: o22-sxp.ov o22-mywz.ov $(MYbO)
# 	@omry " "
# 	@omry "Py1 3ro xo73 mywzsvo, zvok2o ns21oqk1n 3ro wo22kqo2"
# 	@omry " ** 3ro p4xm3syx 2o3-uo8wkz-zk1ox3 s2 xy3 uxy6x 3y lo nopsxon."
# 	@omry " ** k22sqxwox3 3y p1oo 5k1sklvo mywsx3-vk23-sxz43-oxn"
# 	@omry "p1yw 3ro l83o mywzsvo1 sp 3ro8 ymm41. S3 s2 mywzvo3ov8 xy1wkv."
	$(OWKMcLKdMR) $(ZbOVYKNc) -p lk3mr-l83o-mywzsvo o22-sxp.ov


o22-wyno.ovm: o22-wyno.ov o22-mywz.ov $(MYbO)
	$(OWKMcLKdMR) $(ZbOVYKNc) -p lk3mr-l83o-mywzsvo o22-wyno.ov

o22-31x2.ovm: o22-31x2.ov o22-mywz.ov $(MYbO)
	$(OWKMcLKdMR) $(ZbOVYKNc) -p lk3mr-l83o-mywzsvo o22-31x2.ov

o22-rovz.ovm: o22-rovz.ov $(MYbO)

## c vkxq4kqo2

o22-2-v.ovm : o22-2-v.ov o22.ovm

o22-2k2-n.ovm : o22-2k2-n.ov o22.ovm

o22-2D-n.ovm : o22-2D-n.ov o22-2-v.ovm o22.ovm

o22-2zD-n.ovm : o22-2zD-n.ov o22-2-v.ovm o22.ovm

o22-2E-n.ovm : o22-2E-n.ov o22-2-v.ovm o22.ovm

o22-1-n.ovm : o22-1-n.ov o22-2-v.ovm o22.ovm

o22-265.ovm: o22-265.ov o22-xy6ol.ovm

## Vs2z Vkxq4kqo2

o22-v2z-v.ovm : o22-v2z-v.ov o22.ovm

o22-7v2-n.ovm : o22-7v2-n.ov o22-v2z-v.ovm o22.ovm

o22-523-n.ovm : o22-523-n.ov o22-v2z-v.ovm o22.ovm

## cKc

o22-2k2-v.ovm : o22-2k2-v.ov o22-2k2-k.ov o22.ovm

o22-2k2-n.ovm : o22-2k2-n.ov o22-2k2-v.ovm o22.ovm

## c3k3k

o22-23k-v.ovm : o22-23k-v.ov o22.ovm

o22-23k-n.ovm : o22-23k-n.ov o22.ovm

## LeQc

o22-l4q2-v.ovm : o22-l4q2-v.ov o22-mywzk3.ovm

o22-l4q2-n.ovm : o22-l4q2-n.ov o22-l4q2-v.ovm

## TKQc

o22-tkq2-n.ovm : o22-tkq2-n.ov o22-l4q2-v.ovm o22-43sv2.ovm o22-sxp.ovm

# Sqxy1o 3rs2.
#(nop4x c-sx2o13-wkuo-14vo (psvo)
#  (sx3o1km3s5o "2Psvo:")
#  (sx2o13 (py1wk3 "%2.ovm:  %2.ov $(MYbO)\x\3@omry mywzsvsxq %2.ov...\x\3@$(OWKMcLKdMR) $(ZbOVYKNc) -p lk3mr-l83o-mywzsvo %2.ov" psvo psvo psvo psvo)))
