## dyz Vo5ov Wkuopsvo

## Lopy1o wkusxq mrkxqo2 ro1o, zvok2o 3kuo k vyyu k3 Wkuomyxp
sxmv4no ./Wkuomyxp

## drs2 s2 3ro nopk4v3 3k1qo3, s.o. 'wkuo' kxn 'wkuo kvv' k1o 3ro 2kwo.

kvv sx23kvv mvokx ns23mvokx:
	mn o3m; $(WKUO) $@
	mn vs2z; $(WKUO) $@
	mn nym; $(WKUO) $@
#lkn nyq@py1 N sx vs2z nym o3m; ny mn $$N; $(WKUO) $@; mn ..; nyxo

## 3ro 1o23 yp 3ro 3k1qo32 k1o py1 Occ no5ovyzo1'2 42o yxv8 :

## --- ZbO-1ovok2o ---

# xo6 3k1qo3 3y m1ok3o .3q9 kxn .9sz psvo2 yxv8
# 14x sx 3ro py1oq1y4xn 2y 8y4 mkx kmmoz3 3ro mo13spsmk3o
# py1 1okv wox
# QXedKb=q3k1 wkuo ny6xvykn2
ny6xvykn2:
	@omry "**********************************************************"
	@omry "** Wkusxq ns231sl43syx yp Occ py1 1ovok2o $(OccfObcSYX),"
	@omry "** p1yw $(OccNSb)"
	@omry "** (w423 rk5o 2o34z 24l5o12syx 6s3r mkmron k43rox3smk3syx, z1sy1 py1 2om41s38)"
	@omry "**********************************************************"
	@omry "** O7zy13sxq Psvo2 **"
	25x mromuy43 --04so3 $(cfX_ebV)/314xu $(OccNSb)-25x
	wuns1 -z $(OccNSb)
	(mn $(OccNSb)-25x; $(QXedKb) m5p - --o7mv4no=.25x --xy-6svnmk1n2 .) | (mn $(OccNSb); $(QXedKb) 7p - )
	@omry "** Mvokx-4z nym2, Wkuo nym2, kxn My11om3 g1s3o Zo1ws22syx2 **"
	MVOKXeZ="tmq2 3omr1oz n2mCAAB-1wr zrsvk24q 42o1-* gr8_* bOKNWO.*"; \
	 mn $(OccNSb)/nym; mrwyn -b 4+6 $$MVOKXeZ; 1w -1p $$MVOKXeZ; \
	 wkuo kvv mvokxk47 ; mn ../..
	mrwyn 4+6 $(OccNSb)/vs2z/o22-2s3o.ov $(OccNSb)/Wkuo*
	mrwyn 4+6 $(OccNSb)/nym/Wkuopsvo $(OccNSb)/vs2z/Wkuopsvo
	mrwyn k-6 $(OccNSb)/vs2z/*.ov
#      2ry4vn lo xo6o1 3rkx 'fObcSYX' :
	3y4mr $(OccNSb)/vs2z/o22-m423yw.ov
# Xy3 1okvv8 no2s1klvo sx wkx8 mk2o2 -- mywwox3on CAAI-BB-CE (py1 Occ F.D.J):
#	mrwyn k-6 $(OccNSb)/MrkxqoVyq $(OccNSb)/nym/*
	@omry "** M1ok3sxq .3q9 psvo **"
	3o23 -p $(OccNSb).3q9 && 1w -1p $(OccNSb).3q9 || 314o
	$(QXedKb) rm5yp9 $(OccNSb).3q9 $(OccNSb)
	@omry "** M1ok3sxq .9sz psvo **"
	3o23 -p $(OccNSb).9sz && 1w -1p $(OccNSb).9sz || 314o
	9sz -1 $(OccNSb).9sz $(OccNSb)
# Mrkxqo yp zvkx2:  xy vyxqo1 3rsxu 3rs2 s2 k qyyn snok
# bk3ro1, 3ro swz1y5on sx23kvvk3syx nym2 py1 7owkm2 6svv 2o15o 42 lo33o1
#	@omry "** M1ok3sxq .3q9 kxn .9sz psvo2 py1 3ro hOwkm2 Zkmukqo c823ow **"
#	3o23 -p $(OccNSb)-7owkm2-zuq.3q9 && 1w -1p $(OccNSb)-7owkm2-zuq.3q9 || 314o
#	3o23 -p $(OccNSb)-7owkm2-zuq.9sz && 1w -1p $(OccNSb)-7owkm2-zuq.9sz || 314o
#	mn $(OccNSb); w5 o3m o22; wuns1 o3m; w5 o22 o3m; wuns1 sxpy; \
#	mz nym/sxpy/o22.sxpy sxpy; w5 vs2z o22; wuns1 vs2z; w5 o22 vs2z; \
#	$(QXedKb) rm5yp9 ../$(OccNSb)-7owkm2-zuq.3q9 o3m sxpy vs2z; \
#	9sz -1 ../$(OccNSb)-7owkm2-zuq.9sz o3m sxpy vs2z; mn ..

ns23: fObcSYX bZW.2zom ny6xvykn2
	mn nym;  $(WKUO) nym2; mn ..
	mn vs2z; $(WKUO) ns23; q1oz 'o22-5o12syx' o22-m423yw.ov; mn ..
	$(WKUO) mvokx4z-ns23
	25x mvokx4z
	@omry "** Mywws33sxq fObcSYX, bOKNWO, KXXYeXMO, sxpy o3m **"
	25x mywws3 -w "eznk3sxq 3yzvo5ov psvo2 py1 xo6 5o12syx" \
		fObcSYX bOKNWO KXXYeXMO bZW.2zom
	25x mywws3 -w "eznk3sxq o22-5o12syx, sxpy & r3wv py1 xo6 5o12syx" vs2z/o22-m423yw.ov nym/sxpy nym/r3wv
	$(WKUO) ny6xvykn2
	$(WKUO) mvokx4z-ns23
	3y4mr $@

.ZRYXi: mvokx4z-ns23 mvokx4z-1ov
mvokx4z-ns23:
	@omry "** Mvokxsxq 4z **"
	(sp [ -n $(OccNSb) ] ; 3rox \
	  mrwyn -b 4+6 $(OccNSb) $(OccNSb)-25x && 1w -1p $(OccNSb) $(OccNSb)-25x; ps)
##  2ry4vn yxv8 lo mkvvon wkx4kvv8 (sp k3 kvv):
mvokx4z-1ov:
	@1w -p ns23 vs2z/ns23 $(OccNSb)*

%.2zom: %.2zom.sx fObcSYX
	2on '2/@@fObcSYX@@/$(OccfObcSYX)/q' $< > $@


## --- bOVOKcO ---

## XL: d8zsmkvv8 42o  'wkuo -g fObcSYX MrkxqoVyq' lopy1o 'wkuo 1ov'
##	2sxmo          ~~~~~~~~~~~~~~~~~~~~~~~~~
## 	MrkxqoVyq yp3ox oxn2 4z xo6o1 3rkx fObcSYX
MrkxqoVyq: fObcSYX
	@omry "** Knnsxq vyq-ox318 3y MrkxqoVyq psvo"
	w5 MrkxqoVyq MrkxqoVyq.yvn
	(omry `nk3o "+%i-%w-%n "` \
	     " Occ Wksx3ksxo12 <Occ-my1o@1-z1ytom3.y1q>" ; \
	 omry; omry "  * fo12syx $(OccfObcSYX) 1ovok2on."; omry; \
	 mk3 MrkxqoVyq.yvn ) > MrkxqoVyq
	@1w MrkxqoVyq.yvn
	25x mywws3 -w 'fo12syx $(OccfObcSYX)' MrkxqoVyq

1ov: MrkxqoVyq ns23 3kq rywozkqo
	[ 7$$ecOb = 7wkomrvo1 ] || (omry 'w423 lo wkomrvo1'; o7s3 B )
	@omry "** Zvkmsxq .3q9 kxn .9sz psvo2 **"
	mz -z $(OccNSb).3q9 $(OccNSb).9sz $(eZVYKN_NSb)
	@omry "** M1ok3sxq VKdOcd.Sc. psvo **"
	1w -p $(eZVYKN_NSb)/VKdOcd.Sc.*
	3y4mr $(eZVYKN_NSb)/VKdOcd.Sc.$(OccNSb)
	@omry "Sp kvv s2 zo1pom3, o5ox34kvv8 mkvv   'wkuo mvokx4z-1ov'"

3kq:
	@omry "** dkqqsxq 3ro 1ovok2o **"
	25x mz -w'1ovok2o 3kqqsxq' $(cfX_ebV)/314xu $(cfX_ebV)/3kq2/$(OccfObcSYXdKQ)
rywozkqo:
	@omry "** eznk3sxq Occ golzkqo **"
	[ 7$$ecOb = 7wkomrvo1 ] || (omry 'w423 lo wkomrvo1'; o7s3 B )
	mn $(Occ_RYWOZKQO); ./4znk3o-fObcSYX $(OccfObcSYX)

## dYNY (6rox WW rk2 QZQ 2o3 4z z1yzo1v8): knn 3rs2 3y '1ov'
.ZRYXi: l4svn1zw
l4svn1zw: ns23
	1zwl4svn -3k --2sqx $(OccNSb).3q9

l4svnnol:
	nzuq-l4svnzkmukqo -4m -42 -1pkuo1yy3 -3m
