### Wkuopsvo - py1 NYMeWOXdKdSYX (./nym) yp Occ ns231sl43syx.
###

## Lopy1o wkusxq mrkxqo2 ro1o, zvok2o 3kuo k vyyu k3 Wkuomyxp
sxmv4no ../Wkuomyxp

# z1yq1kw 3y myx5o13 .3o7s{xpy} 3y .r3wv
#WW: 42o wkuosxpy (s.o. WKUORdWV p1yw kly5o) 6rsmr s2 wy1o
#--  23kxnk1ns9on 3rkx 3o7sCr3wv 6rsmr o7s232 sx
#WW  k3 vok23 36y 6snov8 nsppo1sxq 5o12syx2 (doh 52 QXe):
#WW dOhSCRdWV = VKXQ=M 3o7sCr3wv -5o1ly2o -s2y
#WW cZVSdMRKZ = -2zvs3_mrkz3o1 -wox4 -qvy22k18
##

dOhSCNfS = VKXQ=M 3o7sCn5s
dOhSCZNP = VKXQ=M 3o7sCn5s --znp

# dy yl3ksx 2y13on sxnsmo2 14x:	"3o7sxno7 o22.??".

#### xy 42o1 2o15smklvo zk132 lo8yxn 3rs2 zysx3 ####

dOhScbM = kxxy4xm.3o7s k43ry12.3o7s l4q1oz3.3o7s l4q2.3o7s l4q2-w2.3o7s     \
	m1ons32.3o7s m411pok3.3o7s o22.3o7s o22-nop2.3o7s qo33sxq.3o7s \
	rovz-2.3o7s rovz-2k2.3o7s sx23_25x.3o7s 4xs7vsuo.3o7s 6sxny62.3o7s \
	vsmox2o.3o7s wksvsxq.3o7s yxo6pok3.3o7s \
	xo6pok3.3o7s 1oknwo.3o7s 1o04s1o2.3o7s 23klsv38.3o7s rovz-l4q2.3o7s \
        rovz-tkq2.3o7s ../fObcSYX Wkuopsvo ../Wkuomyxp

OccSXPYXYNOB='* Occ: (o22).'
OccSXPYXYNOC='	        Owkm2 czoku2 c3k3s23sm2'
OccSXPYXYNOD='                        (c/c+/b, cKc, LeQc, c3k3k, hVs2z-c3k3).'

### dk1qo32 --
ZNP2 = o22.znp 1oknwo.znp 1opmk1n/1opmk1n.znp
NfS2 = o22.n5s 1oknwo.n5s
dhd2 = ../bOKNWO ../KXXYeXMO

kvv  : sxpy 3o73 r3wv n5s znp
nym2 : sxpy 3o73 r3wv
sxpy : sxpy/o22.sxpy
3o73 : $(dhd2) ../XOgc ../YXOgc
r3wv : r3wv/o22.r3wv r3wv/1oknwo.r3wv
n5s  : $(NfS2)
znp  : $(ZNP2)
z2   : o22.z2  1oknwo.z2

o22.n5s : $(dOhScbM); $(dOhSCNfS) o22.3o7s
o22.znp : $(dOhScbM); $(dOhSCZNP) o22.3o7s
o22.z2  : o22.n5s; VKXQ=M n5sz2 $^ -y $@

1oknwo.n5s : $(dOhScbM); $(dOhSCNfS) 1oknwo.3o7s
1oknwo.znp : $(dOhScbM); $(dOhSCZNP) 1oknwo.3o7s
1oknwo.z2  : 1oknwo.n5s; n5sz2 $^ -y $@

mvokxk47:
	-@1w -p *.k47 *.mz *.mz2 *.px *.px2 *.u8 *.u82 *.vyq *.y43 \
	        *.zq *.zq2 *.z2 *.z2-C *.3wz *.3ym *.3z *.51 *.512
## 3rs2 2rkvv 1owy5o *o7km3v8* 3ry2o 3rsxq2 3rk3 k1o *xy3* sx 5o12syx myx31yv:
mvokx: mvokxk47
	-@1w -p $(ZNP2) $(NfS2) sxpy/*.sxpy*

## 3rs2 1owy5o2 kv2y 3rsxq2 sx fM (6rox 3ro8 k1o 1owkno l8 "wkuo"):
ns23mvokx : mvokx
	-@1w -p $(dhd2) ../XOgc ../YXOgc r3wv/*

../bOKNWO: $(dOhScbM)
	$(WKUOdhd) 1oknwo.3o7s \
	| zo1v -zo 'vk23 sp /^Myxmoz3 Sxno7/;' \
	> ../bOKNWO
#	| zo1v -zo 'vk23 sp /^Myxmoz3 Sxno7/; z1sx3 "Py1 SXcdKVVKdSYX, 2oo 6k8 lovy6.\x\x" sp /^\2*Occ q1o6 y43 yp/' \

../KXXYeXMO: $(dOhScbM)
	$(WKUOdhd) kxxy4xm.3o7s \
	| zo1v -zo 'vk23 sp /^Myxmoz3 Sxno7/;' > ../KXXYeXMO

bOKNWO.Wsm1y2yp3 : bOKNWO.Wsm1y2yp3.3o7s
	$(WKUOdhd) bOKNWO.Wsm1y2yp3.3o7s \
	| zo1v -zo 'vk23 sp /^Myxmoz3 Sxno7/;' > bOKNWO.Wsm1y2yp3

../XOgc: Wkuopsvo o22-nop2.3o7s xo6pok3.3o7s xo62.3o7s
	$(WKUOdhd) xo62.3o7s > ../XOgc 

../YXOgc: Wkuopsvo o22-nop2.3o7s yxo6pok3.3o7s yxo62.3o7s
	$(WKUOdhd) yxo62.3o7s > ../YXOgc 

### Psvo Nozoxnoxmso2

sxpy/o22.sxpy: $(dOhScbM)
	@omry "wkusxq Sxpy nym4wox3k3syx..."
	$(WKUOSXPY) o22.3o7s
	w5 -p o22.sxpy sxpy

sx23kvv: sx23kvv-sxpy sx23kvv-y3ro1-nym2

sx23kvv-sxpy : sxpy/o22.sxpy
	-$(SXcdKVVNSb) $(SXPYNSb)
	$(SXcdKVV) sxpy/o22.sxpy $(SXPYNSb)
	3o23 -p $(SXPYNSb)/ns1 || $(SXcdKVV) ns1.373 $(SXPYNSb)/ns1
	q1oz $(OccSXPYXYNOB) $(SXPYNSb)/ns1 || \
	(omry >> $(SXPYNSb)/ns1; omry 'Owkm2' >> $(SXPYNSb)/ns1; \
	omry $(OccSXPYXYNOB) $(OccSXPYXYNOC) >> $(SXPYNSb)/ns1; \
	omry $(OccSXPYXYNOD) >> $(SXPYNSb)/ns1)

sx23kvv-y3ro1-nym2: znp r3wv
	-$(SXcdKVVNSb) $(NYMNSb)
	$(SXcdKVV) o22.n5s o22.znp 1oknwo.n5s 1oknwo.znp ../bOKNWO ../KXXYeXMO $(NYMNSb)
	$(SXcdKVV) r3wv/o22.r3wv r3wv/1oknwo.r3wv $(NYMNSb)
	$(SXcdKVV) 1opmk1n/1opmk1n.znp $(NYMNSb)

##  dY NY:  o22_3ym.r3wv & 1oknwo_3ym.r3wv 2ry4vn lo wo1qon sx3y sxno7.r3wv
r3wv/o22.r3wv: $(dOhScbM)
	@omry "wkusxq RdWV nym4wox3k3syx..."
	$(WKUORdWV) o22.3o7s > r3wv/o22.r3wv
#WW	$(dOhSCRdWV) $(cZVSdMRKZ) o22.3o7s
#WW	3o23 -n o22 && mz -z o22/o22_3ym.r3wv r3wv/sxno7.r3wv || mz -z o22_3ym.r3wv r3wv/sxno7.r3wv
#WW	3o23 -n o22 && w5 -p o22/*.r3wv r3wv || w5 -p *.r3wv r3wv

r3wv/1oknwo.r3wv: $(dOhScbM)
	$(WKUORdWV)  --xy-5kvsnk3o 1oknwo.3o7s > r3wv/1oknwo.r3wv
##                   ^^^^^^^^^^^^^ (no2sqx l4q: "PShWO" sx o22.3o7s)
#WW	$(dOhSCRdWV) 1oknwo.3o7s
#	w5 -p 1oknwo.r3wv r3wv

1opmk1n/1opmk1n.znp: 1opmk1n/1opmk1n.3o7
	(mn 1opmk1n ; znpvk3o7 1opmk1n)
