#!/usr/local/bin/bash
# provides the total nb of packets sent
if [[ $# != 1 ]]
then 
	echo "USAGE: $0 <in/out>"
else
	if [[ x"$1" != x"in" ]]
	then # out case
	    POS="4"
	else
	    POS="3"
	fi
#	netstat -I athn0 -c 1 -b -w 1 | tail -1 | awk 'BEGIN {IFS=" "} { print ($'$POS')*4/(1024*1024) }'
	netstat -I bge0 -c 1 -b -w 1 | tail -1 | awk 'BEGIN {IFS=" "} { print ($'$POS')*4/(1024*1024) }'
fi
