LOCAL_REMOTE_MACHINE=localhost
LOCAL_LOCAL_PORT=22
REMOTE_LOCAL_MACHINE=localhost
REMOTE_LOCAL_PORT=10000
REMOTE_SSH_PORT=2222
LOCAL_USER=guigui
REMOTE_USER=guigui

exe=`ssh-agent`
${exe}
ssh-add
## test auth
##ssh -p 2222 guigui@localhost
export AUTOSSH_DEBUG=1
export AUTOSSH_GATETIME=0
export AUTOSSH_PORT=20000
autossh -N -R ${REMOTE_LOCAL_PORT}:${REMOTE_LOCAL_MACHINE}:${LOCAL_LOCAL_PORT} -p ${REMOTE_SSH_PORT} ${REMOTE_USER}@${LOCAL_REMOTE_MACHINE}
# -f