#!/bin/bash
if [[ $# != 1 ]]
then 
	echo "USAGE: $0 <CPU number>"
else
	CPUNB=$1
#	top -d 0 -i -b -n 1 | grep "Cpu${CPUNB}" | awk '{ print $6 }' | cut -d '%' -f 1 | awk '{ print (1-$1/100) }'
	retVal=`cat /proc/stat | grep cpu${CPUNB} | awk '{ print ($2/1000*100/4) }'` # 1rst 1000 is because value is in 1/1000th of sec, 2nd 100 is for percentage

    if [[ "$retVal"x != ""x ]] ; then
	echo $retVal
    else
	echo "0.0" # Just in case next command does return nothing, prevents awesome freeze
    fi
fi
