#!/bin/bash
if [[ $# != 1 ]]
then 
	echo "USAGE: $0 <root/home>"
else
	if [[ x"$1" != x"root" ]]
	then # home case
	    size=`df -h | grep '/home'`
	    if [[ "$size"x != ""x ]] ; then
		retVal=`echo $size | cut -d '%' -f 1 | awk '{ print $5/100 }'`
	    else
		retVal=""
	    fi
	else
	    size=`df -h | grep -e '/$'`
	    if [[ "$size"x != ""x ]] ; then
		retVal=`echo $size | cut -d '%' -f 1 | awk '{ print $5/100 }'`
	    else
		retVal=""
	    fi
	fi

    if [[ "$retVal"x != ""x ]] ; then
	echo $retVal
    else
	echo "0.0" # Just in case next command does return nothing, prevents awesome freeze
    fi
fi
