#!/bin/bash
# provides the total nb of packets sent
if [[ $# != 1 ]]
then 
	echo "USAGE: $0 <in/out>"
else
	if [[ x"$1" != x"in" ]]
	then # out case
	    POS="4"
	else
	    POS="8"
	fi
	retVal0=`netstat -i eth0 | grep eth0 | awk '{ print ($'$POS')*8/(3600) }'`
	if [[ "$retVal0" == "" ]] ; then retVal0="0.0" ; fi
	retVal1=`netstat -i eth1 | grep eth1 | awk '{ print ($'$POS')*8/(3600) }'`
	if [[ "$retVal1" == "" ]] ; then retVal1="0.0" ; fi
	retVal=`echo "($retVal0+$retVal1)" | bc -l`

	if [[ "$retVal"x != ""x ]] ; then
	    echo $retVal
	else
	    echo "0.0" # Just in case next command does return nothing, prevents awesome freeze
	fi
fi
