#!/bin/bash
if [[ $# != 0 ]]
then 
    echo "USAGE: takes no args"
else
    retVal=$(echo "`cat /sys/class/power_supply/BAT0/energy_now`/`cat /sys/class/power_supply/BAT0/energy_full`" | bc -l)

    if [[ "$retVal"x != ""x ]] ; then
	echo $retVal
    else
	echo "0.0" # Just in case next command does return nothing, prevents awesome freeze
    fi
fi
