#!/bin/bash
# provides the total nb of packets sent
## TODO: get the list of ifaces that are "up" (have a "inet addr") and
## sum ip infos only from those ifaces

ET0=eth0
ET1=eth1
WI1=wlp3s0
WI2=wlxb0487a8eda3c


if [[ $# != 1 ]]
then
    echo "USAGE: $0 <in/out>"
else
    if [[ x"$1" != x"in" ]]
    then # out case
        POS="4"
    else
        POS="8"
    fi
    retVal0=`netstat -i ${ET0} | grep ${ET0} | awk '{ print ($'$POS')*8/(3600) }'`
    if [[ "$retVal0" == "" ]] ; then retVal0="0.0" ; fi
    retVal1=`netstat -i ${ET1} | grep ${ET1} | awk '{ print ($'$POS')*8/(3600) }'`
    if [[ "$retVal1" == "" ]] ; then retVal1="0.0" ; fi
    retVal2=`netstat -i ${WI1} | grep ${WI1} | awk '{ print ($'$POS')*8/(3600) }'`
    if [[ "$retVal2" == "" ]] ; then retVal2="0.0" ; fi
    retVal3=`netstat -i ${WI2} | grep ${WI2} | awk '{ print ($'$POS')*8/(3600) }'`
    if [[ "$retVal3" == "" ]] ; then retVal3="0.0" ; fi
    retVal=`echo "($retVal0+$retVal1+$retVal2+$retVal3)" | bc -l`

    if [[ "$retVal"x != ""x ]] ; then
        echo $retVal
    else
        echo "0.0" # Just in case next command does return nothing, prevents awesome freeze
    fi
fi
