#!/bin/bash
if [[ $# != 0 ]]
then
    echo "USAGE: takes no args"
else
    used=`free | sed -n 2p | awk '{ print $3 }'`
    total=`free | sed -n 2p | awk '{ print $2 }'`
    retVal=`echo "($used/$total)" | bc -l`
    if [[ "$retVal"x != ""x ]] ; then
    echo $retVal
    else
    echo "0.0" # Just in case next command does return nothing, prevents awesome freeze
    fi
fi
