svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/presans-commons/trunk presans-commons
svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/presans-crawling/trunk presans-crawling
svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/presans-indexing/trunk presans-indexing
svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/presans-lib/trunk presans-lib
svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/presans-machinelearning/trunk presans-machinelearning
svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/presans-searching/trunk presans-searching
svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/presans-jsofia/trunk presans-jsofia
svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/presans-xsearch/branches/sofia2 sofia2
svn co svn+ssh://gmuller@k2.presans.com/home/svn/repos/dist dist
