#!/bin/bash
# A function that runs a process only if it is not already running
function run_only_once()
{
    IFS=" " read -a splitted <<< $1
    progName=`basename ${splitted[0]}`
    if [[ "$progName" =~ "sudo" ]]
    then
        progName="`basename ${splitted[1]}`"
    fi
    mesg=$(mygrep "$progName " || eval ${splitted[*]} 2>&1) # Use "$progName " to ensure we do not get pids of similarily-named processes
    echo -e "${progName}:\n ${mesg}" >> /tmp/mesg_${progName}
}

function mygrep() {
    ps aux | grep -F "$1" | grep -Fv grep
}
