#!/bin/bash
# A function that runs a process only if it is not already running
function run_only_once()
{
    IFS=" " read -a splitted <<< $1
    progName=`basename ${splitted[0]}`
    if [[ "$progName" =~ "sudo" ]]
    then
        progName="$(basename "${splitted[1]}")"
    fi
    # echo "PROG_NAME: $progName"
    # out=$(pgrep -f "$progName(\\s+|$)")
    # echo -e "PGREP: $out ($?)"
    mesg=$(pgrep -f "$progName(\\s+|$)" || eval "${splitted[*]}" 2>&1)
    echo -e "${progName}:\n ${mesg}" >> /tmp/mesg_${progName}
}
