#!/bin/bash
network=""
while [[ "$network"x == ""x ]] ; do
    network=`ifconfig | grep "inet addr" | grep -v -F "127.0.0.1"`
    sleep 2;
done
echo "To: sexxxenator@gmail.com
From: myipadresstoday@gmail.com
Subject: The IP of the day!

`ifconfig`

------------------------------------

`. /home/guillaume/Softs/get_external_ip.sh`

------------------------------------

`dmesg`

------------------------------------

`cat /var/log/syslog`


I'll get you, stealer!" | ssmtp gm@presans.com
