#!/usr/bin/env bash

network=""
while [[ "$network"x == ""x ]] ; do
    network=`ifconfig | grep "inet addr" | grep -v -F "127.0.0.1"`
    sleep 2;
done
echo "To: sexxxenator@gmail.com
From: myipadresstoday@gmail.com
Subject: The IP of the day!

`ifconfig`

------------------------------------

`. ~/Softs/get_external_ip.sh`

------------------------------------

$(cards=$(iwconfig 2>&1 | grep -vF "no wireless extensions"  | cut -d " " -f 1 | sed '/^$/d') ; for c in ${cards} ; do iwlist wlxb0487a8eda3c scanning ; done)

------------------------------------

`dmesg`

------------------------------------

`cat /var/log/syslog`

------------------------------------

I'll get you, stealer!" | ssmtp gm@presans.com
