#!/bin/bash

# For good programs
export no_proxy=localhost,127.0.0.1,*.example.com
export http_proxy=http://kuzh.polytechnique.fr:8080/
export https_proxy=https://kuzh.polytechnique.fr:8080/
export ftp_proxy=ftp://kuzh.polytechnique.fr:8080/
# export socks_proxy=socks://kuzh.polytechnique.fr:8080/

# For other programs (system-wide java proxy settings & other gtk-based progs...)
# Configuration
gsettings set org.gnome.system.proxy.http host 'kuzh.polytechnique.fr'
gsettings set org.gnome.system.proxy.http port 8080
gsettings set org.gnome.system.proxy.http use-authentication false
gsettings set org.gnome.system.proxy use-same-proxy false
gsettings set org.gnome.system.proxy.https host 'kuzh.polytechnique.fr'
gsettings set org.gnome.system.proxy.https port 8080
gsettings set org.gnome.system.proxy.ftp host 'kuzh.polytechnique.fr'
gsettings set org.gnome.system.proxy.ftp port 8080
gsettings set org.gnome.system.proxy.socks host ''
gsettings set org.gnome.system.proxy.socks port 0

# Enabling
gsettings set org.gnome.system.proxy mode 'manual'
gsettings set org.gnome.system.proxy.http enabled true
gsettings set org.gnome.system.proxy ignore-hosts "[ 'localhost', '127.0.0.0/8' ]"

### For apt-get/synaptic [SHOULD BE ROOT for this to work...]
/bin/cp -f /etc/apt/apt.conf.withproxy /etc/apt/apt.conf

# For Chrome (that uses dconf settings)
touch ~/.proxy_is_set
dconf write '/system/proxy/http/host' '"kuzh.polytechnique.fr"'
dconf write '/system/proxy/http/port' '8080'
dconf write '/system/proxy/https/host' '"kuzh.polytechnique.fr"'
dconf write '/system/proxy/https/port' '8080'
dconf write '/system/proxy/ftp/host' '"kuzh.polytechnique.fr"'
dconf write '/system/proxy/ftp/port' '8080'
dconf write '/system/proxy/socks/host' '""'
dconf write '/system/proxy/socks/port' '0'

# For programs that use old gnome settings
gconftool-2 --set -t string '/system/proxy/ftp_host' "kuzh.polytechnique.fr"
gconftool-2 --set -t integer '/system/proxy/ftp_port' "8080"
gconftool-2 --set -t string '/system/proxy/secure_host' "kuzh.polytechnique.fr"
gconftool-2 --set -t integer '/system/proxy/secure_port' "8080"
gconftool-2 --set -t string '/system/proxy/socks_host' ""
gconftool-2 --set -t integer '/system/proxy/socks_port' "0"
gconftool-2 --set -t string '/system/proxy/mode' "manual"
gconftool-2 --set -t string '/system/http_proxy/host' "kuzh.polytechnique.fr"
gconftool-2 --set -t integer '/system/http_proxy/port' "8080"
gconftool-2 --set -t bool '/system/http_proxy/use_http_proxy' true
gconftool-2 --set -t bool '/system/http_proxy/use_authentication' false
