#!/bin/bash

. /home/guillaume/Softs/runonlyonce

# TODO: use finer detection of where we are: ping -c 1 verspertine.xtec.polytechnique.fr
currIP=`ifconfig wlan0 | grep 'inet addr'  | cut -d ':' -f 2 | cut -d ' ' -f 1 | grep '10\.0\.0\.'`
if [[ "${currIP}"x != ""x ]]
then
  su -c "pkill update_indicator" guillaume
  . /home/guillaume/Softs/set_proxy
  su -c ". /home/guillaume/Softs/set_proxy" guillaume
  su -c ". /home/guillaume/Softs/runonlyonce ; . /home/guillaume/Softs/start_updatemanager" guillaume
  #touch /home/guillaume/_NETWORK_STARTUP_RUN_`date "+%F-%T"`
else
  su -c ". /home/guillaume/Softs/unset_proxy" guillaume
  . /home/guillaume/Softs/unset_proxy
fi
