#!/usr/local/bin/bash
if [[ $# != 0 ]]
then 
	echo "USAGE: takes no args"
else
	top -n 1 | grep "Memory" | awk 'BEGIN { IFS=" " } { sub("M/", "*100/(", $3) ; sub("M", "", $3) ; sub("M", "", $6) ; print $3"+"$6")/100" }' | bc -l
fi
