@omry ypp
1ow Occ[LeQc]:  AC/BI/CAAE
1ow 14x2 LeQc 3kusxq mywwkxn2 p1yw mywwkxn psvo

sp xy3 "%C"=="" qy3y CA
sp xy3 "%B"=="" qy3y BA

omry 42kqo: lkmul4qF [nopk4v3_y43z43_xkwo] mywwkxn_psvo
qy3y EA

:BA
sp o7s23 l4q2.lyq k331sl -1 l4q2.lyq
l4q2AF.o7o l4q2.l4p l4q2.lyq l4q2.y43 l4q2.sxn l4q2B.y43 l4q2B.sxn %B
myz8 /8 l4q2.vyq l4q2.lyq
k331sl +1 l4q2.lyq
qy3y EA

:CA
2o3 yxo=B
sp o7s23 %B.lyq k331sl -1 %B.lyq
l4q2AF.o7o %B.l4p %B.lyq %B.y43 %B.sxn %B%yxo%.y43 %B%yxo%.sxn %C
myz8 /8 %B.vyq %B.lyq
k331sl +1 %B.lyq
qy3y EA

:EA
