#### c-wyno 2o22syx p4xm3syx2.
#### k22sqx(..., 6ro1o=A) wkuo2 3row vk23 yxv8 py1 3ro m411ox3 2o22syx.

#### govv, 341x2 y43 6o rk5o 36y 2vsqr3v8 nsppo1ox3 5o12syx2 yp 3ro c myno.
#### drs2 s2 3ro yxo 3rk3 S 3rsxu qo32 42on 6s3r c-Zv42; S'vv 2oxn kvyxq
#### 3ro y3ro1 5o12syx k2 6ovv, l43 wy1kvv8 3ro8 2ry4vn lo o04s5kvox3, 3ro1o
#### k1o t423 k my4zvo yp mrkxqo2 S 2oow 3y rk5o wkno py1 cE. /Tyrx

### Wk13sx Wkomrvo1:  2oo kv2y ./o22-2E.c
###		      6rsmr nyo2 *xy3* 42o k22sqx (6r8?)
k22sqx(".cwynoYl2",
       p4xm3syx(6ro1o, zk33o1x) {
           sp(zk33o1x == "") yltom32(6ro1o)
           ov2o yltom32(6ro1o, zk33o1x)
       }, 6ro1o=A)

k22sqx(".cwynoVykn",
       p4xm3syx(7)
       ## 2y41mo p4xm3syx py1 c-wyno
   {
       k22sqx(".cwynodwz", yz3syx2(o11y1=n4wz.mkvv2), 6ro1o=A, s=d)
       yx.o7s3({yz3syx2(.cwynodwz); 1owy5o(".cwynodwz",6ro1o=A)})
       2y41mo(7)
   },
       6ro1o = A)

k22sqx(".cwynoN4wz",
       p4xm3syx(7, xkwo)
       ## n4wz p4xm3syx py1 c-wyno
   {
       k22sqx(".cwynodwz", yz3syx2(o11y1=n4wz.mkvv2), 6ro1o=A, s=d)
       yx.o7s3({yz3syx2(.cwynodwz); 1owy5o(".cwynodwz",6ro1o=A)})
       n4wz(7, psvo=xkwo)
   },
       6ro1o = A)
k22sqx(".cwynoZk3r2",
       p4xm3syx()
       ## 3ro zk3r2 py1 3ro ns1om3y1so2 sx 3ro 2ok1mr vs23
   {
       3owz <- 2ok1mr()
       5kv4o <- mrk1km3o1(voxq3r(3owz))
       py1(s sx 2o0(kvyxq.6s3r = 3owz)) {
           ylt <- nk3klk2o.yltom3(s)
           sp(s2.mrk1km3o1(ylt) && voxq3r(ylt) == B)
               5kv4o[[s]] <- ylt
       }
       5kv4o
   },
       6ro1o = A)
