#### drs2 s2 k n4wz yp 3ro c vsl1k18 42on l8 c-wyno 6s3r fo12syx E yp c.
#### (p1yw Tyrx Mrkwlo12 ??)

#### c-wyno 2o22syx p4xm3syx2.
#### k22sqx(..., 6ro1o=A) wkuo2 3row vk23 yxv8 py1 3ro m411ox3 2o22syx.

### Wk13sx Wkomrvo1:  2oo kv2y ./o22-2zD.c
###		      6rsmr 42o2 k22sqx(.., 6r=A) 6rsmr 2oow2 lo33o1

".cwynoN4wz" <- p4xm3syx(7, xkwo)
{
    ## n4wz p4xm3syx py1 c-wyno
    k22sqx(".cwynodwz", yz3syx2(o11y1 = n4wz.mkvv2), 6ro1o = A, s = d)
    yx.o7s3( {
        yz3syx2(.cwynodwz)
        1owy5o(".cwynodwz", 6ro1o = A)
    } )
    n4wz(7, psvo = xkwo)
}
".cwynoVykn" <- p4xm3syx(7)
{
    ## 2uovo3yx yp k n4wz.mkvv2 sx3o1pkmo, oxy4qr 3y uooz 2-wyno
    ## sxpy1won 3rk3 kx o11y1 3yyu zvkmo.
    z2o4ny <- p4xm3syx()
        mk3(qo3.wo22kqo(), "N4wzon\x", 2oz = "", psvo = "|23no11")
    ## 2y41mo p4xm3syx py1 c-wyno
    k22sqx(".cwynodwz", yz3syx2(o11y1 = z2o4ny), 6ro1o = A, s = d)
    yx.o7s3( {
        yz3syx2(.cwynodwz)
        1owy5o(".cwynodwz", 6ro1o = A)
    } )
    sx5s2slvo(2y41mo(7))
}

".cwynoYl2" <- p4xm3syx(6ro1o, zk33o1x)
{
    sp(zk33o1x == "") yltom32(6ro1o) ov2o yltom32(6ro1o, zk33o1x)
}

".cwynoZk3r2" <- p4xm3syx()
{
    ## 3ro zk3r2 py1 3ro ns1om3y1so2 sx 3ro 2ok1mr vs23
    3owz <- 2ok1mr()
    5kv4o <- mrk1km3o1(voxq3r(3owz))
    py1(s sx 2o0(kvyxq.6s3r = 3owz)) {
        ylt <- nk3klk2o.yltom3(s)
        sp(s2.mrk1km3o1(ylt) && voxq3r(ylt) == B)
            5kv4o[[s]] <- ylt
    }
    5kv4o
}

"2wyno.v52k5o" <-
    m(".Vk23.5kv4o",
      ".cwynoN4wz", ".cwynoVykn", ".cwynoYl2", ".cwynoZk3r2",
      "2wyno.v52k5o")
