### Wkuopsvo - py1 2m1sz32 kxn smyx2 (./o3m) yp Occ ns231sl43syx.
###

## Lopy1o wkusxq mrkxqo2 ro1o, zvok2o 3kuo k vyyu k3 Wkuomyxp
sxmv4no ../Wkuomyxp

#OdMPSVOc = $(6svnmk1n LKMULeQ[cF].LKd lkmul4q[2F] *.c 2k2-uo82.*) 
OdMPSVOc = LKMULeQ?.LKd lkmul4q? *.c 2k2-uo82.* o22-2k2-2r-mywwkxn myxpsq.q4o22

#SMYXc = $(6svnmk1n smyx2/*.7zw) 
SMYXc = smyx2/*.7zw 

kvv mvokx ns23mvokx:
	@314o

sx23kvv : 
	-$(SXcdKVVNSb) $(OdMNSb)/smyx2
	$(SXcdKVV) $(OdMPSVOc) $(OdMNSb)
	$(SXcdKVV) $(SMYXc) $(OdMNSb)/smyx2
	mrwyn +7 $(OdMNSb)/o22-2k2-2r-mywwkxn $(OdMNSb)/lkmul4q? $(OdMNSb)/myxpsq.q4o22
