@omry ypp
1ow Occ[LeQc]:  AC/BD/CAAD
1ow 14x2 LeQc 3kusxq mywwkxn2 p1yw mywwkxn psvo

sp xy3 "%D"=="" qy3y DA
sp xy3 "%C"=="" qy3y CA
sp xy3 "%B"=="" qy3y BA

omry 42kqo: lkmul4q2 [[x4wlo1_yp_lsx2] nopk4v3_y43z43_xkwo] mywwkxn_psvo
qy3y EA

:BA
l4q2AGAD.o7o DC l4q2 %B
sp o7s23 l4q2.lyq k331sl -1 l4q2.lyq
myz8 /8 l4q2.vyq l4q2.lyq
k331sl +1 l4q2.lyq
qy3y EA

:CA
l4q2AGAD.o7o DC %B %C
sp o7s23 %B.lyq k331sl -1 %B.lyq
myz8 /8 %B.vyq %B.lyq
k331sl +1 %B.lyq
qy3y EA

:DA
l4q2AGAD.o7o %B %C %D
sp o7s23 %C.lyq k331sl -1 %C.lyq
myz8 /8 %C.vyq %C.lyq
k331sl +1 %C.lyq

:EA
